= How to handle inital ssh-logins

== Document State: Draft

Currently this document only reflects some of the thoughts from our Community-meeting on 2020-09-02. Anybody involved and with own ideas and arguments is urged to add these here.

== Problem statement:

The machine that is doing the deployment, needs to access all the nodes to install via ssh.
The Installer will be a docker container, thats started via a shell script. So we have some options, on how to aquire access.


== Target

We want to use ssh private/public key pairs. If the customer has not yet established public/private keypairs, we are able to create these for our usecase
Our container must create its own, new private-key on start. We don't want to deliver a pre-created privatekey with the container.

== Not in Focus

We don't want to rollout "thePerfectAccessManagementSolution[tm]" with all the bells and whistles.

== Discussed options

. User is asked for Username/Password. The installer then can create a new ssh-keypair use these information, to use and deploy them to the machines for later use

. User already has working ssh-keypairs. We could reuse these by mounting/injecting these into the container (maybe autodetected?)

.. The simplest case: no passphrase protection on the keys. simply works

.. If there are passphrase proteced Private-Keys the user has to be asked for the passphrase

.. maybe the user is using SSH-Agent - can we simply detect the socket of the ssh-agent and access it from the container?


== Arguments

. Option: Username/Password
+
Pro::
- Works straight forward in every scenario
- no complexity for different scenarios

Contra::
- seems more insecure
- creating additional public-keys in customers infrastructure

  Implementational Effort:

. Option: Reuse of existing ssh-keypairs, a customer already rolled out

.. Option:
+
Pro:::
- fast solution in default usecases that simply works

Contra:::
- PreReq: user has to have already rolled out public-keys
- PreReq: private keys accessible and not passphrase-protected

  Implementational Effort:

.. Option:
+
Pro:::
- fast solution like 2a)

Contra:::
- implementation of passphrase handling necessary
- PreReq: user has to have already rolled out public-keys

  Implementational Effort:

.. Option:
+
Pro:::
- if SSH-Agent is in use, its the premium solution.

Contra:::
- PreReq: user has to have already rolled out public-keys
- (minor) implement detection and use of SSH_AUTH_SOCKET

  Implementational Effort:

== Issues & Comments

* Solution 1) has the lowest barrier for users, just starting to setup linux and vanilla. Keypairs are not uncommon at all, but are used on a more expert level.

* SSH it trying hard, to make you create keypairs with passprases. Its to be assumed, that lot of users have passphrases on their private keys

* In all cases, that involve passing secret information to SSH like passwords or passphrases, ssh actively tries to force an interactive keyboard session. Simple pipes or expect-scripts don't work in these cases and you have to work around that in any case

* for private keys we should assume that the ssh config and keys are stored in $HOME/.ssh
+ Any other directory is a significant change from defaults and can not be focused on for the mvp

* Detecting SSH-Agent is indeed quite easy, and the installer-script should at least give this a try: If the environment variable `SSH_AUTH_SOCK` is set, then it points to the socket. If the user can read this file, then he has access to the SSH-Agent. Injecting this socket into the container is possible, and relaying the variable into the container is no problem.

== Jurlind: Summary of my thoughts, based on the elaborated information from Jan.

Option 1): As ssh-keys might be "uncommon" to the client, we should support this option. From an implementation perspective we have following options:

1a) User enters on the installer UI the same username/password for all systems to log via ssh.

This is the "easiest" option, for us as well as for the client. I would also refrain from creating additional ssh-key pairs, because this would add complexity, and not increase security. Username/passwords still exist on those systems, even after we install and delete the created ssh-keys. Therefore, we do not really need this extra step. 

1b) User enters on the installer UI different username/password for each system to log via ssh.

This could be a client internal requirement, to not use the same username/password in different systems. Therefore, it seems necessary to support this option also. If we want to do it, is another question. From a security perspective, I would argue that is even better to go with option a) i.e. have the same temporary, username/password on the different systems for the installation process, and delete that user from the systems when finished. However, I see this as the responsibilty of the client, as the tool is being installed at the client, and the client is initiating installation process. We are only responsible to provide this argument, and make cleare where responsibilites lie.

Option 2): As the client might have internal requirments forbbiding username/password via ssh, we should support this option. From an implement perspective we have similar cases as above, i.e 2a) one key-pair for all systems; 2b) different key-pair for each system. As the key-pair is, ideally must be only temporary as the username/password in 1), I would recommend to implement only 2a. This means that the client is responsible to delete/remove the keys from the systems after the installation is finished.

As ssh-keys might be protected with a passphrase, due to internal requirements, it should be supported to enter this passphrase on the UI. If left blank, than installer assumes ssh-key has no phassphrase. In this case I would refrain from extracting the ssh-key from an ssh-agent, this only adds complexity, and it does not really increase security. If ssh-keys are uncommon, ssh-agents even more. Adding the passphrase once at the agent, or once more in the UI of the installer, it does not make a big difference. 

At the end we recommend to use temporary credentials, be those username/password, or ssh-key (with or without phassphrase), that should be removed/deleted by the client after installation is finished. Thus, we could implement a warning at the end of the intallation, like "Warning: Please make sure to remove/delete credentials used for the installation from the systems."


== Decision

No decision yet
