---
- name: Get Node Kubernetes version
  command: kubectl get nodes --no-headers -o custom-columns=VERSION:.status.nodeInfo.kubeletVersion {{ hostname }}
  register: node_kubelet_version_command

- name: Add node to the update group
  block:
    - name: Add master to the update_master group
      add_host:
        name: "{{ hostname }}"
        group: update_master
      when: hostname in groups['master']
    - name: Add node to the update_nodes group
      add_host:
        name: "{{ hostname }}"
        group: update_nodes
      when: hostname in groups['worker']
  when:
    - node_kubelet_version_command.stdout is defined
    - (node_kubelet_version_command.stdout | replace('v', '')) is version(kubernetes.version, 'lt')
