---
- name: get nodes in cluster
  command: kubectl get nodes -o name
  register: worker
  ignore_errors: yes

- name: Add all hosts running this playbook to the done group
  add_host:
    name: '{{ item }}'
    group: install_nodes
  when: 'worker.rc != 0 or item not in worker.stdout'
  loop: "{{ groups.worker }}"      

- name: Add all hosts running this playbook to the done group
  add_host:
    name: '{{ item }}'
    group: install_master
  when: 'worker.rc != 0 or item not in worker.stdout'
  loop: "{{ groups.master }}"
