---
- name: get nodes in cluster
  command: kubectl get nodes -o name
  register: worker
  args:
    ignore_errors: true

- name: Add new nodes running this playbook to the install_nodes group
  add_host:
    name: "{{ item }}"
    group: install_nodes
  when: "worker.rc != 0 or item not in worker.stdout"
  loop: "{{ groups.worker }}"

- name: Add new masters running this playbook to the install_master group
  add_host:
    name: "{{ item }}"
    group: install_master
  when: "worker.rc != 0 or item not in worker.stdout"
  loop: "{{ groups.master }}"
