---
- name: Get Nodes in Kubernetes Cluster
  command: kubectl get nodes -o name
  register: current_worker
  ignore_errors: true

- name: Add nodes that do not exist in the Kubernetes Cluster to install_ groups
  when: current_worker.rc != 0
  block:
    - name: Add new masters running this playbook to the install_master group
      add_host:
        name: "{{ item }}"
        group: install_master
      when: "item not in current_worker.stdout"
      loop: "{{ groups.master }}"

    - name: Add new nodes running this playbook to the install_nodes group
      add_host:
        name: "{{ item }}"
        group: install_nodes
      when: "item not in current_worker.stdout"
      loop: "{{ groups.worker }}"

- name: Get Nodes with Version in Kubernetes Cluster
  shell: kubectl get nodes --no-headers -o custom-columns=VERSION:.status.nodeInfo.kubeletVersion | sort | uniq
  register: current_nodes_version
  ignore_errors: true

- name: Check if any nodes need an update
  include_tasks: 00-1_check_update.yaml
  with_items: "{{ groups.master + groups.worker }}"
  when:
    - current_nodes_version.stdout is defined
    - current_nodes_version.stdout != kubernetes.version

- debug:
    var: groups.update_master

- name: Test
  fail: {}
