---
- name: Check if distribution is supported
  fail:
    msg: This disribution is currently not supported by VanillaStack
  when: ansible_distribution != 'Debian'

- name: Preinstall packages
  apt:
    name:
      - gnupg
      - python3

- include_tasks: configure_debian_repos.yaml

- name: Install necessary packages
  apt:
    name:
      - curl
      - fail2ban
      - firmware-linux
      - firmware-linux-nonfree
      - git
      - gnupg
      - iproute2
      - jq
      - libseccomp2
      - lvm2
      - nfs-common
      - python3-jmespath
      - python3-kubernetes
      - python3-passlib
      - python3-pip
      - systemd-timesyncd
      - tar
      - vim
    autoclean: true
    update_cache: true
    autoremove: true
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: Install packages to masters
  apt:
    name:
      - helm
    autoclean: true
    update_cache: true
    autoremove: true
  register: result
  until: result is not failed
  retries: 10
  delay: 10
  when: "'master' in group_names"

- name: Upgrade OS
  apt:
    autoclean: true
    update_cache: true
    autoremove: true
    upgrade: full
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: Upgrade all packages to the latest version
  apt:
    autoclean: true
    update_cache: true
    autoremove: true
    name: "*"
    state: latest
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: configure timesyncd for ntp
  template:
    src: etc/systemd/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0444
  notify: restart timesyncd
  when: ntp.manage_timesyncd

- name: Uninstall ntp package
  apt:
    name: ntp
    state: absent
  when: ntp.manage_timesyncd

- name: Enable fstrim.timer
  systemd:
    name: fstrim.timer
    state: started
    enabled: true

- name: Make sure, domain search is not set
  lineinfile:
    regexp: "^(.*)search(.*)$"
    state: absent
    path: /etc/resolv.conf

- name: make sure, unattended upgrades is removed
  package:
    name: unattended-upgrades
    state: absent

- include_tasks: kube_crio_install.yaml

- name: Save kubeversion to YAML file
  lineinfile:
    path: /tmp/kubeversion.yml
    regexp: "^(.*)version(.*)$"
    line: "version: {{ kube_version | regex_replace('-[0-9]+', '') }}"
    create: true

- name: Fetch kubeversion.yml
  become: true
  fetch:
    src: "/tmp/kubeversion.yml"
    dest: "/tmp/kubeversion.yml"
    flat: true
  run_once: true

- name: Configure kubelet
  lineinfile:
    path: /etc/default/kubelet
    regexp: "^(.*)KUBELET_EXTRA_ARGS(.*)$"
    line: 'KUBELET_EXTRA_ARGS=--container-runtime=remote --container-runtime-endpoint="unix:///var/run/crio/crio.sock"'
    create: true

- include_tasks: configure_crio.yaml

- name: "Check for installed packages"
  package_facts:
    manager: "auto"

- name: Disable Firewall
  systemd:
    name: "{{ item }}"
    masked: true
    enabled: false
    state: stopped
  when: "item in ansible_facts.packages"
  loop:
    - "firewalld"
    - "ufw"

- name: Disable rpcbind
  systemd:
    name: "rpcbind"
    state: stopped
    enabled: false

- name: Copy Fail2ban jail.conf
  template:
    src: etc/fail2ban/jail.conf.j2
    dest: /etc/fail2ban/jail.conf

- name: Enable Fail2ban
  systemd:
    name: "fail2ban"
    enabled: true
    state: restarted

- name: Set nofile soft limit
  community.general.pam_limits:
    limit_type: soft
    limit_item: nofile
    value: 1048576
    domain: "*"

- name: Set nofile hard limit
  community.general.pam_limits:
    limit_type: hard
    limit_item: nofile
    value: 1048576
    domain: "*"

- name: Add api name to hosts file
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ loadbalancerIP }} api.{{ clusterTLDomain }}"

- name: Copy disable transparent huge pages service unit file
  copy:
    src: etc/systemd/system/disable-transparent-huge-pages.service
    dest: /etc/systemd/system/disable-transparent-huge-pages.service
    owner: root
    group: root
    mode: 0644

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable and start disable transparent huge pages service
  systemd:
    name: disable-transparent-huge-pages
    state: restarted
    enabled: true
