---
- name: Check if distribution is supported
  fail:
    msg: This disribution is currently not supported by VanillaStack
  when: ansible_distribution != 'Debian'

- name: Preinstall packages
  apt:
    name:
      - gnupg
      - python3

- name: copy sources.list
  copy:
    src: sources.list
    dest: /etc/apt/sources.list

- name: Add key from keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  loop:
    - 93C4A3FD7BB9C367
    - 8BECF1637AD8C79D
  retries: 3
  delay: 1
  register: result
  until: result is success

- name: Add key for cri-o repos
  apt_key:
    url: "{{ item }}"
  loop:
    - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    - "https://baltocdn.com/helm/signing.asc"
    - "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.19/Debian_10/Release.key"
    - "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/Release.key"
  retries: 3
  delay: 1
  register: result
  until: result is success

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main"
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    - "deb https://baltocdn.com/helm/stable/debian/ all main"
    - "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.19/Debian_10/ /"
    - "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /"
  retries: 3
  delay: 1
  register: result
  until: result is success

- name: Install neccessary packages
  apt:
    name:
      - gnupg
      - git
      - vim
      - lvm2
      - jq
      - curl
      - tar
      - ansible
      - needrestart
      - helm
      - nfs-common
      - iproute2
      - python3-pip
      - python3-kubernetes
      - python3-passlib
      - fail2ban
      - python3-jmespath
    update_cache: yes
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: install pip modules
  pip:
    name:
      - pyhelm
      - openshift
    extra_args: --ignore-installed

- name: Upgrade all packages to the latest version
  apt:
    update_cache: yes
    upgrade: yes
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: configure timesyncd for ntp
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0444
  notify: restart timesyncd
  when: ntp.manage_timesyncd

- name: make sure, domain search is not set
  lineinfile:
    regexp: '^(.*)search(.*)$'
    state: absent
    path: /etc/resolv.conf

- name: make sure, unattended upgrades is removed
  package:
    name: unattended-upgrades
    state: absent

### build crio
- name: install build packages
  apt:
    name:
      - btrfs-progs
      - golang
      - runc
      - containers-common
      - git
      - golang-go
      - libassuan-dev
      - libdevmapper-dev
      - libglib2.0-dev
      - libc6-dev
      - libgpgme11-dev
      - libgpg-error-dev
      - libseccomp-dev
      - libsystemd-dev
      - libselinux1-dev
      - pkg-config
      - go-md2man
      - cri-o-runc
      - libudev-dev
      - software-properties-common
      - gcc
      - make
      - conmon

- name: clone crio repository
  git:
    repo: 'https://github.com/cri-o/cri-o'
    dest: /tmp/crio
    version: "release-{{ kubernetes.version }}"

- name: crio make
  community.general.make:
    chdir: /tmp/crio

- name: crio make install
  community.general.make:
    chdir: /tmp/crio
    target: install

- name: copy crio systemd file
  copy:
    src: crio.service
    dest: /lib/systemd/system/crio.service

- name: reload systemd
  systemd:
    daemon_reload: true
### end build crio

- name: get latest kube version
  shell: apt-cache madison kubeadm | grep {{ kubernetes.version }} | head -1 | tr -s ' ' | cut -d ' ' -f4
  register: apt_output

- name: get kubeversion
  set_fact:
    versions: "{{ apt_output.stdout }}"

- name: Install packages
  apt:
    pkg:
      - "kubelet={{ versions }}"
      - "kubeadm={{ versions }}"
      - "kubectl={{ versions }}"
      - libgtk2.0-0
    update_cache: yes
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: mark packages as hold
  command: "apt-mark hold {{ item }}" 
  with_items:
    - "kubelet"
    - "kubeadm"
    - "kubectl"

- name: configure crio
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: '^(.*)conmon =(.*)$'
    line: 'conmon = "/usr/bin/conmon"'
    backrefs: yes

## Bug needs to be tracked
- name: remove seccomp from crio
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: '^(.*)seccomp_profile =(.*)$'
    line: 'seccomp_profile = ""'
    backrefs: yes

- name: fix runc runtime path in crio config
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: '^  runtime_path =(.*)$'
    line: '  runtime_path = "/usr/sbin/runc"'
    backrefs: yes

- name: configure kubelet
  lineinfile:
    path: /etc/default/kubelet
    regexp: '^(.*)KUBELET_EXTRA_ARGS(.*)$'
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --container-runtime=remote --container-runtime-endpoint="unix:///var/run/crio/crio.sock"'
    create: true

- name: Set CRI-O cgroups driver
  lineinfile:
    path: /etc/crio/crio.conf
    state: present
    regexp: '^cgroup_manager =.*'
    line: 'cgroup_manager = "systemd"'

- name: Set CRI-O default_ulimits
  blockinfile:
    path: /etc/crio/crio.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      default_ulimits = [
          "nofile=16384:24576",
          "nproc=8192:8192"
      ]

- name: Set CRI-O seccomp profile path
  lineinfile:
    path: /etc/crio/crio.conf
    state: present
    regexp: '^seccomp_profile =.*'
    line: 'seccomp_profile = ""'

- name: Set CRI-O global auth
  lineinfile:
    path: /etc/crio/crio.conf
    state: present
    regexp: '^global_auth_file =.*'
    line: 'global_auth_file = "/etc/crio/auth.json"'
  when: commercial.enabled

- name: remove preconfigures crio.conf from dpkg
  file:
    path: /etc/crio/crio.conf.d/01-crio-runc.conf
    state: absent

- name: Set CRI-O seccomp profile path
  lineinfile:
    path: /etc/crio/crio.conf
    state: present
    regexp: '^pids_limit*.'
    line: 'pids_limit = 8192'

- name: "Check for installed packages"
  package_facts:
    manager: "auto"

- name: Disable Firewall
  systemd:
    name: "{{ item }}"
    masked: true
    enabled: false
    state: stopped
  when: "item in ansible_facts.packages"
  loop:
    - "firewalld"
    - "ufw"

- name: Disable rpcbind
  systemd:
    name: "rpcbind"
    state: stopped
    enabled: no

- name: Copy Fail2ban jail.conf
  template:
    src: jail.conf.j2 
    dest: /etc/fail2ban/jail.conf
 
- name: Enable Fail2ban
  systemd:
    name: "fail2ban"
    enabled: true
    state: restarted

- name: Set nofile soft limit
  community.general.pam_limits:
    limit_type: soft
    limit_item: nofile
    value: 1048576

- name: Set nofile hard limit
  community.general.pam_limits:
    limit_type: hard
    limit_item: nofile
    value: 1048576
