---
- name: Check if distribution is supported
  fail:
    msg: This disribution is currently not supported by VanillaStack
  when: ansible_distribution != 'Debian'

- name: Preinstall packages
  apt:
    name:
      - gnupg
      - python3

- name: Clear apt sources.list
  copy:
    content: ""
    dest: /etc/apt/sources.list

- name: List files in apt sources.list.d directory
  find:
    path: /etc/apt/sources.list.d
    file_type: file
    excludes:
      - repo_vanillastack_cloudical_net.list
    register: found_sources_lists

- name: Remove other apt sources.list.d lists
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ found_sources_lists.files }}"
  when: found_sources_lists is defined and found_sources_lists.files is defined

- name: Add Cloudical APT repositories
  template:
    src: etc/apt/sources.list.d/repo_vanillastack_cloudical_net.list
    dest: /etc/apt/sources.list.d/repo_vanillastack_cloudical_net.list
    owner: root
    group: root
    mode: 0644

- name: Add key for Cloudical APT repositories
  apt_key:
    url: "{{ item }}"
  loop:
    - "{{repositories.package_repository}}/public-gpg-key"
  retries: 3
  delay: 1
  register: result
  until: result is success

- name: Add Cloudical Repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb {{repositories.package_repository}} {{staging_tag}}-pip3 main"
    - "deb {{repositories.package_repository}} {{staging_tag}}-ansible main"
    - "deb {{repositories.package_repository}} {{staging_tag}}-debian-buster-main main"
    - "deb {{repositories.package_repository}} {{staging_tag}}-debian10-crio-{{kubernetes.crioVersion}} main"
    - "deb {{repositories.package_repository}} {{staging_tag}}-helm main"
    - "deb {{repositories.package_repository}} {{staging_tag}}-kubernetes-xenial main"
    - "deb {{repositories.package_repository}} {{staging_tag}}-cloudfoundry main"
  retries: 3
  delay: 1
  register: result
  until: result is success

- name: Install neccessary packages
  apt:
    name:
      - gnupg
      - git
      - vim
      - lvm2
      - jq
      - curl
      - tar
      - ansible
      - needrestart
      - helm
      - cf-cli
      - nfs-common
      - iproute2
      - python3-openshift
      - python3-pyhelm
      - python3-pip
      - python3-kubernetes
      - python3-passlib
      - fail2ban
      - python3-jmespath
      - libseccomp2
    autoclean: true
    update_cache: true
    autoremove: true
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: Upgrade OS
  apt:
    autoclean: true
    update_cache: true
    autoremove: true
    upgrade: full
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: Upgrade all packages to the latest version
  apt:
    autoclean: true
    update_cache: true
    autoremove: true
    name: "*"
    state: latest
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: configure timesyncd for ntp
  template:
    src: etc/systemd/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0444
  notify: restart timesyncd
  when: ntp.manage_timesyncd

- name: Uninstall ntp package
  apt:
    name: ntp
    state: absent
  when: ntp.manage_timesyncd

- name: Enable fstrim.timer
  systemd:
    name: fstrim.timer
    state: started
    enabled: true

- name: make sure, domain search is not set
  lineinfile:
    regexp: "^(.*)search(.*)$"
    state: absent
    path: /etc/resolv.conf

- name: make sure, unattended upgrades is removed
  package:
    name: unattended-upgrades
    state: absent

- name: get latest kube version
  shell: apt-cache madison kubeadm | grep {{ kubernetes.version }} | head -1 | tr -s ' ' | cut -d ' ' -f4
  register: apt_output

- name: get kubeversion
  set_fact:
    versions: "{{ apt_output.stdout }}"

- name: save kubeversion
  lineinfile:
    path: /tmp/kubeversion.yml
    regexp: "^(.*)version(.*)$"
    line: "version: {{ versions | replace ('-00','') }}"
    create: true

- name: fetch kubeversion
  become: true
  fetch:
    src: "/tmp/kubeversion.yml"
    dest: "/tmp/kubeversion.yml"
    flat: true
  run_once: true

- name: Install packages
  apt:
    pkg:
      - "kubelet={{ versions }}"
      - "kubeadm={{ versions }}"
      - "kubectl={{ versions }}"
      - "cri-o"
      - "cri-o-runc"
      - libgtk2.0-0
    update_cache: true
    autoclean: true
    autoremove: true
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: mark packages as hold
  command: "apt-mark hold {{ item }}"
  with_items:
    - "kubelet"
    - "kubeadm"
    - "kubectl"
    - "cri-o"
    - "cri-o-runc"

- name: configure crio
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: "^(.*)conmon =(.*)$"
    line: 'conmon = "/usr/bin/conmon"'
    backrefs: true

- name: fix runc runtime path in crio config
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: "^runtime_path =(.*)$"
    line: 'runtime_path = "/usr/lib/cri-o-runc/sbin/runc"'
    backrefs: true

- name: configure kubelet
  lineinfile:
    path: /etc/default/kubelet
    regexp: "^(.*)KUBELET_EXTRA_ARGS(.*)$"
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --container-runtime=remote --container-runtime-endpoint="unix:///var/run/crio/crio.sock"'
    create: true

- name: Set CRI-O cgroups driver
  lineinfile:
    path: /etc/crio/crio.conf
    state: present
    regexp: "^cgroup_manager =.*"
    line: 'cgroup_manager = "systemd"'

- name: Set CRI-O default_ulimits
  blockinfile:
    path: /etc/crio/crio.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      default_ulimits = [
          "nofile=16384:24576",
          "nproc=8192:8192"
      ]

#- name: Set CRI-O seccomp profile path
#  lineinfile:
#    path: /etc/crio/crio.conf
#    state: present
#    regexp: '^seccomp_profile =.*'
#    line: 'seccomp_profile = ""'
#    line: 'seccomp_profile = "/usr/share/containers/seccomp.json"'

- name: Set CRI-O default seccomp profile as true
  lineinfile:
    path: /etc/crio/crio.conf
    state: present
    regexp: "^seccomp_use_default_when_empty =.*"
    line: "seccomp_use_default_when_empty = true"
#    line: 'seccomp_profile = "/usr/share/containers/seccomp.json"'

- name: Set CRI-O global auth
  lineinfile:
    path: /etc/crio/crio.conf
    state: present
    regexp: "^global_auth_file =.*"
    line: 'global_auth_file = "/etc/crio/auth.json"'
  when: commercial.enabled

- name: remove preconfigures crio.conf from dpkg
  file:
    path: /etc/crio/crio.conf.d/01-crio-runc.conf
    state: absent

- name: Set CRI-O PIDs limit
  lineinfile:
    path: /etc/crio/crio.conf
    state: present
    regexp: "^pids_limit*."
    line: "pids_limit = 8192"

- name: "Check for installed packages"
  package_facts:
    manager: "auto"

- name: Disable Firewall
  systemd:
    name: "{{ item }}"
    masked: true
    enabled: false
    state: stopped
  when: "item in ansible_facts.packages"
  loop:
    - "firewalld"
    - "ufw"

- name: Disable rpcbind
  systemd:
    name: "rpcbind"
    state: stopped
    enabled: false

- name: Copy Fail2ban jail.conf
  template:
    src: etc/fail2ban/jail.conf.j2
    dest: /etc/fail2ban/jail.conf

- name: Enable Fail2ban
  systemd:
    name: "fail2ban"
    enabled: true
    state: restarted

- name: Set nofile soft limit
  community.general.pam_limits:
    limit_type: soft
    limit_item: nofile
    value: 1048576
    domain: "*"

- name: Set nofile hard limit
  community.general.pam_limits:
    limit_type: hard
    limit_item: nofile
    value: 1048576
    domain: "*"

- name: set hosts if kubeapi is not dns resolvable
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ loadbalancerIP }} api.{{ clusterTLDomain }}"

- name: Copy disable transpartent huge pages service unit file
  copy:
    src: etc/systemd/system/disable-transparent-huge-pages.service
    dest: /etc/systemd/system/disable-transparent-huge-pages.service
    owner: root
    group: root
    mode: 0644

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable and start disable transpartent huge pages service
  systemd:
    name: disable-transparent-huge-pages
    state: restarted
    enabled: true
