---
- name: Load kernel modules for Kubernetes
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Persist kernel modules loading for Kubernetes
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: true
  with_items:
    - br_netfilter
    - overlay

- name: Tweak sysctl settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: true
  loop: "{{ sysctls | dict2items }}"
  vars:
    sysctls:
      net.bridge.bridge-nf-call-ip6tables: 1
      net.bridge.bridge-nf-call-iptables: 1
      net.ipv4.ip_forward: 1
      net.core.somaxconn: 65536
      fs.inotify.max_user_instances: 5120
      fs.inotify.max_user_watches: 1572864

# See https://github.com/cilium/cilium/issues/10645
- name: Set net.ipv4.conf.*.rp_filter to 0 for systemd 245 workaround
  when: cluster_sdn == "cilium"
  sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_file: /etc/sysctl.d/99-z-rp_filter.conf
    reload: true
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter

- name: Disable Swap
  command: swapoff -a

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'

# Why? Because a customer and VanillaStack should always the full "address" to a repository
- name: Copy custom CRI-O registries config
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  loop:
    - etc/containers/registries.conf
    - etc/containers/registries.conf.d/000-shortnames.conf

- name: Remove default CNI configs
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/cni/net.d/100-crio-bridge.conf"
    - "/etc/cni/net.d/200-loopback.conf"

- name: Make sure crio service is running
  systemd:
    state: restarted
    enabled: true
    name: crio

- name: Make sure kubelet service is running
  systemd:
    state: restarted
    enabled: true
    name: kubelet

- name: "Reboot machine to get latest updates"
  reboot:
