---
- name: Wait for etcd to be ready
  command: kubectl wait --namespace=kube-system --for=condition=ready pods etcd-{{ item }} --timeout=10s
  retries: 180
  delay: 10
  register: result
  until: result.rc == 0
  loop: "{{ groups.master }}"

- name: Sleep 10 seconds
  pause:
    seconds: 10

- name: Deploy cilium chart
  kubernetes.core.helm:
    name: cilium
    chart_version: "{{ kubernetes.cilium.version }}"
    chart_ref: vanillastack/cilium
    release_namespace: kube-system
    values: "{{ lookup('template', 'cilium-values.yaml.j2') | from_yaml }}"
    wait: true
    wait_timeout: "{{ kubernetes.cilium.waitTimeout }}"
    update_repo_cache: true

- name: Deploy Cilium MTU Manifest if non zero value provided
  when: kubernetes.cilium.manual_mtu != 0
  block:
    - name: Copy file
      ansible.builtin.template:
        src: cilium_mtu_update.yaml
        dest: /tmp/mtu_update.yaml
    - name: Apply MTU Update
      command: kubectl apply -f /tmp/mtu_update.yaml

- name: Wait for control-plane pods become ready
  command: kubectl wait --namespace=kube-system --for=condition=Ready pods --all --timeout=10s
  retries: 180
  delay: 10
  register: result
  until: result.rc == 0

- name: Manage access creds
  block:
    - name: Copy ssh key to master1
      copy:
        src: "{{ ansible_ssh_private_key_file }}"
        dest: /tmp/tempkey.pem

    - name: Add ssh key as secret
      shell: >
        kubectl create secret generic --namespace kube-system --save-config --dry-run=client management-ssh-key --from-file=id_rsa=/tmp/tempkey.pem -o yaml | kubectl apply --namespace kube-system -f -

    - name: Make sure, ssh key is removed
      file:
        path: /tmp/tempkey.pem
        state: absent
  when: ansible_ssh_private_key_file is defined and ansible_ssh_private_key_file|length>0
