---
- name: label worker nodes
  command: >
    kubectl label nodes "{{ item }}" node-role.kubernetes.io/worker=worker \
    openvswitch=enabled linuxbridge=enabled ceph-rgw=enabled
  loop: "{{ groups.install_nodes }}"
  ignore_errors: true

- name: label storage nodes
  command: kubectl label nodes "{{ item }}" rook=enabled
  loop: "{{ groups.install_nodes }}"
  when: item in groups.storage
  ignore_errors: true
