---
- include_tasks: configure_debian_repos.yaml

- include_tasks: deb_kube_crio_install.yaml
  when: ansible_distribution == 'Debian' and ansible_architecture == "x86_64"

- name: Run kubeadm upgrade plan
  command: kubeadm upgrade plan

- name: Run kubeadm upgrade apply v{{ kubernetes.version }}
  command: kubeadm upgrade apply --yes v{{ kubernetes.version }} {% if kubernetes.ignorePreflightErrors is defined and kubernetes.ignorePreflightErrors|length > 0 %} --ignore-preflight-errors={{ kubernetes.ignorePreflightErrors|join(", ") }} {% endif %}

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted

- name: Restart CRI-O when the packages installed changed
  systemd:
    name: crio
    state: restarted
  when:
    - crio_apt_result is defined
    - crio_apt_result.changed is defined
    - crio_apt_result.changed

- name: Sleep a few seconds for good measure
  pause:
    seconds: "{{ kubernetes.updateSleepSeconds | int }}"
