---
- include_tasks: 09-3_drain_node.yaml
  vars:
    hostname: inventory_hostname

- include_tasks: configure_debian_repos.yaml

- include_tasks: kube_crio_install.yaml

- name: Run kubeadm upgrade node
  command: kubeadm upgrade node

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted

- include_tasks: 09-3_uncordon_node.yaml
  vars:
    hostname: inventory_hostname
