---
- include_tasks: 09-3_drain_node.yaml
  vars:
    hostname: "{{ inventory_hostname }}"

- include_tasks: configure_debian_repos.yaml

- include_tasks: kube_crio_install.yaml

- name: Uncordon node if is master
  include_tasks: 09-3_uncordon_node.yaml
  vars:
    hostname: "{{ inventory_hostname }}"
  when: inventory_hostname in groups.update_master

- name: Run kubeadm upgrade node
  command: kubeadm upgrade node

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted

- name: Restart CRI-O when the packages installed changed
  systemd:
    name: crio
    state: restarted
  when:
    - kube_crio_apt_result is defined
    - kube_crio_apt_result.changed is defined
    - kube_crio_apt_result.changed

- include_tasks: 09-3_uncordon_node.yaml
  vars:
    hostname: "{{ inventory_hostname }}"

- name: Sleep a few seconds for good measure
  pause:
    seconds: 5
