---
- name: Get available Kubernetes version
  shell: apt-cache madison kubeadm | grep {{ kubernetes.version }} | head -1 | tr -s ' ' | cut -d ' ' -f4
  register: kubeversion_apt_output

- name: Set Kubernetes version variable
  set_fact:
    kube_version: "{{ kubeversion_apt_output.stdout }}"

- name: Get available CRI-O version
  shell: apt-cache madison cri-o | grep {{ kubernetes.crioVersion }} | head -1 | tr -s ' ' | cut -d ' ' -f4
  register: crioversion_apt_output

- name: Set CRI-O Package version
  set_fact:
    crio_package_version: "{{ crioversion_apt_output.stdout }}"

- name: Unhold packages
  command: apt-mark unhold {{ item }}
  with_items:
    - "kubelet"
    - "kubeadm"
    - "kubectl"
    - "cri-o"
    - "cri-o-runc"

- name: Install kube packages
  apt:
    pkg:
      - "kubelet={{ kube_version }}"
      - "kubeadm={{ kube_version }}"
      - "kubectl={{ kube_version }}"
    update_cache: true
    autoclean: true
    autoremove: true
  register: kube_apt_result
  until: kube_apt_result is not failed
  retries: 10
  delay: 10

- name: Install cri-o packages
  apt:
    pkg:
      - "cri-o={{ crio_package_version }}"
      - "cri-o-runc={{ kubernetes.crioRuncVersion }}"
    update_cache: true
    autoclean: true
    autoremove: true
  register: crio_apt_result
  until: crio_apt_result is not failed
  retries: 10
  delay: 10

- name: Hold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "kubelet"
    - "kubeadm"
    - "kubectl"
    - "cri-o"
    - "cri-o-runc"

- name: Check if kubeadm has the expected version
  command: kubeadm version
  register: local_kubeadm_version

- name: Fail when kubeadm version is not the expected version
  fail:
    msg: "The host {{ inventory_hostname }} did not have the expected kubeadm version {{ kubernetes.version }} installed after the package update process!"
  when:
    - kubernetes.version not in local_kubeadm_version.stdout
