---
velero:
  enabled: false
  version: v1.10.2
  chartVersion: 3.1.5
  namespace: velero
  backend: minio # minio|aws
  resources:
    requests:
      cpu: "1000m"
      memory: "3Gi"
    limits:
      cpu: "1000m"
      memory: "6Gi"
  restic:
    resources:
      requests:
        cpu: "125m"
        memory: "3Gi"
      limits:
        cpu: "1000m"
        memory: "5Gi"
  aws:
    bucketName: velero
    snapshotBucketName: kubernetes-pv
    region: <region name>
    publicURL: <public url>
    s3URL: <s3 url>
    accessKey: <access key>
    secretKey: <secret key>
  minio:
    enabled: true
    chartVersion: 5.0.7
    nfs:
      size: 50Gi
      server: <NFS server ip>
      path: <NFS path>
    accessKey: <access key>
    secretKey: <secret key>
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "1024Mi"
  schedules:
    k8s-cluster:
      schedule: 15 */4 * * *
      template:
        excludedResources:
        - pvcs
        - pvs
        hooks: {}
        includeClusterResources: true
        includedNamespaces:
        - '*'
        #includedResources:
        #- '*'
        storageLocation: default
        ttl: 336h0m0s
