---
velero:
  enabled: false
  version: v1.8.1
  chartVersion: 2.29.0
  namespace: velero
  backend: minio
  minio:
    enabled: true
    chartVersion: 3.6.2
    nfs:
      size: 50Gi
      server: <NFS server ip>
      path: <NFS path>
    accessKey: <access key>
    secretKey: <secret key>
  aws:
    bucketName: velero
    snapshotBucketName: kubernetes-pv
    region: <region name>
    publicURL: <public url>
    s3URL: <s3 url> 
    accessKey: <access key>
    secretKey: <secret key>
  schedules:
    k8s-cluster:
      schedule: 15 */4 * * *
      template:
        excludedResources:
        - pvcs
        - pvs
        hooks: {}
        includeClusterResources: true
        includedNamespaces:
        - '*'
        #includedResources:
        #- '*'
        storageLocation: default
        ttl: 336h0m0s
