---
- name: Install elasticsearch
  community.kubernetes.helm:
    name: elasticsearch
    chart_ref: vanillastack/elasticsearch
    release_namespace: kube-logging
    values: "{{ lookup('template', 'elastic_values.yml.j2') | from_yaml }}"
