---
- name: Create kibana user apache
  htpasswd:
    path: /tmp/kibana_auth
    name: "{{ efkstack.kibana.user }}"
    password: "{{ efkstack.kibana.password }}"
    owner: "{{ efkstack.kibana.system_user }}"
    mode: 0640

- name: Slurp auth file
  slurp:
    src: /tmp/kibana_auth
  register: kibana_auth_slurp

- name: Create secret kibana
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: kibana-basic-auth
        namespace: kube-logging
      type: Opaque
      data:
        auth: "{{ kibana_auth_slurp.content }}"

- name: Install kibana
  community.kubernetes.helm:
    name: kibana
    chart_ref: vanillastack/kibana
    release_namespace: kube-logging
    values: "{{ lookup('template', 'kibana_values.yml.j2') | from_yaml }}"
    create_namespace: true
    wait: true
