---
- name: Install packages
  ansible.builtin.package:
    state: present
    name:
      - keepalived

- name: Put configuration file for keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart keepalived
  tags: config_keepalived
