---
- name: Install basic packages
  package:
    state: present
    name:
      - haproxy

- name: create bridge traffic config
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/ipbind.conf
    reload: true
  loop: "{{ sysctls | dict2items }}"
  vars:
    sysctls:
      net.ipv4.ip_nonlocal_bind: 1

#- name: Start reading wildcard certificate
#  include_vars: vars/wildcard_.pem.yml

#- name: Copy wildcard certificate in /etc/ssl/private/
#  copy:
#     content: "{{ private_key_content }}"
#     dest: /etc/ssl/private/wildcard.pem
#     owner: root
#     group: root
#     mode: 0600

- name: "Create haproxy config file"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: true
    owner: root
    mode: 0644
  notify:
    - restart haproxy
  tags:
    - haproxy_config
