---
# defaults file for deploy-kubernetes

kubernetes:
  init_opts: ""
  kubeadm_opts: ""
  clusterName: kubernetes
  version: "1.23.14"
  crioVersion: "1.23"
  crioRuncVersion: "1.0.1~0"
  helm_version: "v3.3.1"
  pod_cidr: "10.0.0.0/8"
  drainTimeout: "10m"
  ignoreDrainErrors: true
  cilium:
    version: v1.11.2
    waitTimeout: 10m
  ignorePreflightErrors: []

ntp:
  manage_timesyncd: true
  # we have applied already for a vendor-zone "vanilla.pool.ntp.org" for
  # the use with vanillastack, because no vendor should deliver by
  # default with pool.ntp.org. As soon as we get affirmation this must
  # be changed
  server: pool.ntp.org

vanillastack_upload_cluster_config: false
