---
# defaults file for deploy-kubernetes

kubernetes:
  dashboard:
    coreDomain: "k8sboard.{{ clusterTLDomain }}"
    chartVersion: "6.0.6"
    replicas: 1
  clusterName: kubernetes
  # if the patch version is omitted, the latest available will be used (e.g., 1.23 -> 1.23.17).
  version: "1.27"
  crioVersion: "1.27"
  crioRuncVersion: "1.0.1~2"
  helm_version: "3.11.2"
  init_opts: ""
  kubeadm_opts: ""
  drainTimeout: "10m"
  updateSleepSeconds: 90
  ignoreDrainErrors: true
  ignorePreflightErrors: []

cluster_pod_cidr: "10.0.0.0/8"
cluster_service_cidr: "10.96.0.0/12"

cni:
  cilium:
    version: v1.12.13
    waitTimeout: 120s
    proxyReplacement: "strict" # possible values: "disabled", "probe", "partial", "strict"
    manual_mtu: 0 # This Value Sets the MTU for cilium and applies it to a deamonset watching the mtu

ntp:
  manage_timesyncd: true
  # we have applied already for a vendor-zone "vanilla.pool.ntp.org" for
  # the use with vanillastack, because no vendor should deliver by
  # default with pool.ntp.org. As soon as we get affirmation this must
  # be changed
  server: pool.ntp.org

vanillastack_upload_cluster_config: false

offline_install: false
