---
- name: create namespaces
  kubernetes.core.k8s:
    name: "{{item}}"
    api_version: v1
    kind: Namespace
    state: present
  with_items: 
    - "{{rbac.namespaces}}"

- name: create user
  include_tasks: create_user.yaml
  with_items:
    - "{{rbac.users}}"

- name: copy kubeconfigs
  ansible.builtin.fetch:
    src: "kubeconfigs/kubeconfig_{{item}}"
    dest: "/tmp/kubeconfigs-{{clusterTLDomain}}/kubeconfig_{{item}}"
  with_items:
    - "{{rbac.users}}"

- name: create global ClusterRole
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'global-clusterrole.yaml.j2') | from_yaml }}"

- name: create ClusterRole ClusterRoleBinding
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'global-clusterrolebinding-clusterroles.yaml.j2') | from_yaml }}"

- name: create global ClusterRoleBinding
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'global-clusterrolebinding.yaml.j2') | from_yaml }}"

- name: create ClusterRole
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'clusterrole.yaml.j2') | from_yaml }}"

- name: create namespace rolebindings
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'namespace-rolebinding.yaml.j2') | from_yaml }}"
  with_items:
    - "{{rbac.namespaces}}"

- name: create serviceaccounts
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'serviceaccounts.yaml.j2') | from_yaml }}"
  loop: "{{rbac.serviceAccounts|default([])}}"
  loop_control:
    loop_var: sa

- name: create serviceaccounts clusterrole
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'serviceaccounts-clusterrole.yaml.j2') | from_yaml }}"
  loop: "{{rbac.serviceAccounts|default([])}}"
  loop_control:
    loop_var: sa

- name: create serviceaccounts clusterrolebindings
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'serviceaccounts-clusterrolebinding.yaml.j2') | from_yaml }}"
  loop: "{{rbac.serviceAccounts|default([])}}"
  loop_control:
    loop_var: sa
