---
- name: Upgrade all packages to the latest version
  package:
    name: "*"
    state: latest
  retries: 10
  delay: 30
  when: ansible_os_family == 'Debian'

- name: Install Polyverse Repos
  shell: "curl -s https://repo.polyverse.io/cli | sh -s install {{ polyverse.key }}"
  when: ansible_os_family == 'Debian'

- name: Reinstall polymorphed packages on Debian and restart Server
  shell: curl https://repo.polyverse.io/cli | bash -s replace-installed-elf
  when: ansible_os_family == 'Debian'

- name: "Reboot machine to get latest updates"
  reboot:
  when: ansible_os_family == 'Debian'
