---
- name: Deploy Redis
  kubernetes.core.helm:
    name: redis-cluster
    release_namespace: "{{redis.namespace}}"
    create_namespace: true
    chart_ref: "vanillastack/redis-cluster"
    chart_version: "{{redis.chartVersion}}"
    values: "{{ lookup('template', 'redis.yaml.j2') | from_yaml }}"
  retries: 3
  delay: 10

- name: Deploy Redis ServiceMonitor
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'redis-servicemonitor.yaml.j2') | from_yaml }}"
    state: present

- name: Deploy Redis PrometheusRule
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'redis-prometheusrules.yaml.j2') | from_yaml }}"
    state: present
