image: "harbor.cloudical.net/vanillastack/ansible-base:6ef964e3"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SAST_EXCLUDED_PATHS: "docs"
  SECRET_DETECTION_EXCLUDED_PATHS: "docs"
  SEARCH_MAX_DEPTH: 50

stages:
  - test
  - reset_env
  - run_playbook

reset_environment:
  stage: reset_env
  extends: .prepare_playbook
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  allow_failure: true
  script:
    - ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i inventory type_reset_cluster.yaml

run_playbook:
  stage: run_playbook
  extends: .prepare_playbook
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  interruptible: true
  allow_failure: true
  script:
    - ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i inventory type_vanillastack_deploy.yaml

include:
  - template: Security/SAST.gitlab-ci.yml

.prepare_playbook:
  before_script:
    - echo -e "TODO redeploy vm webhook \nPreparing environment"
    - echo "Root Dir = $CI_PROJECT_DIR"
    - echo "Pipeline Source = $CI_PIPELINE_SOURCE"
    - ls -ahl
    - mkdir ~/.ssh && echo "$SSH_KEY"|base64 -d>~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - mv samples/group_vars group_vars
    - cp $VANILLASTACK_INVENTORY "$(pwd)/inventory"
    - yq -i '.reset_environment = true' group_vars/all/container_vars.yaml
    - yq -i '.install_haproxy = true' group_vars/all/container_vars.yaml
    - yq -i ".clusterTLDomain = \"$VANILLASTACK_CLUSTER_TLD\"" group_vars/all/container_vars.yaml
    - yq -i ".loadbalancerIP = \"$VANILLASTACK_LOADBALANCER_IP\"" group_vars/all/container_vars.yaml
    - yq -i e '.ansible_ssh_private_key_file += "~/.ssh/id_rsa"' group_vars/all/container_vars.yaml
    - yq -i e '.kubernetes.cilium.manual_mtu = 1400' group_vars/all/kubernetes.yaml
    - "sed -i 's/minutes: 5/minutes: 1/' roles/deploy-rook/tasks/main.yaml"
    - ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i inventory type_prepare_installnode.yaml
