---
image: "harbor.vanillastack.io/vanillastack/vanilla-ubuntu-base:20201211"
services:
  - docker:18.09.7-dind
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_HOST: tcp://localhost:2375
  SAST_EXCLUDED_PATHS: "docs"
  SECRET_DETECTION_EXCLUDED_PATHS: "docs"
  SEARCH_MAX_DEPTH: 50

stages:
  - gen_version
  - test
  - run_playbook_centos8
  - run_playbook_debian10
  - release

gen_version:
  stage: gen_version
  interruptible: false
  script:
    - echo "VERSION=$(date +'%Y%m')-$CI_COMMIT_SHORT_SHA" > vars.env
    - cat vars.env
  artifacts:
    reports:
      dotenv: vars.env

run_playbook_centos8:
  only:
    refs:
      - testing
  stage: run_playbook_centos8
  interruptible: true
  allow_failure: true
  script:
    - curl $WEBHOOK_REDEPLOY_CENTOS8 && sleep 60
    - mkdir ~/.ssh && echo "$SSH_KEY"|base64 -d>~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - mv group_vars.testing group_vars
    - sed -i "s/POLYVERSE_KEY/${POLYVERSE_KEY}/g" group_vars/all/additional.yaml
    - sed -i "s/REGISTRY_KEY/${HARBOR_COMMERCIAL_KEY}/g" group_vars/all/container_vars.yaml
    - if [ "$COMMUNITY" == true ]; then yq -Yi .commercial.enabled='false' group_vars/all/container_vars.yaml; fi
    - ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i inventory.testing type_vanillastack_deploy.yaml

run_playbook_debian10:
  only:
    refs:
      - testing
  stage: run_playbook_debian10
  interruptible: true
  allow_failure: true
  script:
    - curl $WEBHOOK_REDEPLOY_DEBIAN10 && sleep 60
    - mkdir ~/.ssh && echo "$SSH_KEY"|base64 -d>~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - mv group_vars.testing group_vars
    - sed -i "s/POLYVERSE_KEY/${POLYVERSE_KEY}/g" group_vars/all/additional.yaml
    - sed -i "s/REGISTRY_KEY/${HARBOR_COMMERCIAL_KEY}/g" group_vars/all/container_vars.yaml
    - if [ "$COMMUNITY" == true ]; then yq -Yi .commercial.enabled='false' group_vars/all/container_vars.yaml; fi
    - ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i inventory.testing type_vanillastack_deploy.yaml

release:
  only:
    refs:
      - master
  stage: release
  interruptible: false
  release:
    tag_name: "$VERSION"
    description: "VanillaStack stable release $VERSION"
  script:
    - echo "Publish release $VERSION"
  image: registry.gitlab.com/gitlab-org/release-cli

include:
  - template: Security/SAST.gitlab-ci.yml
#  - template: Security/Secret-Detection.gitlab-ci.yml
