= Licenses

The following licenses are used in the project

Frontend "Installer"

- ...
- ...

Backend "Installer"

- *cookie-parser*, https://www.npmjs.com/package/cookie-parser: MIT
- *debug*, https://www.npmjs.com/package/debug: MIT
- *dotenv*, https://www.npmjs.com/package/dotenv: BSD-2-Clause
- *express*, https://www.npmjs.com/package/express: MIT
- *morgan*, https://www.npmjs.com/package/morgan: MIT
- *swagger-jsdoc*, https://www.npmjs.com/package/swagger-jsdoc: MIT
- *swagger-ui-express*, https://www.npmjs.com/package/swagger-ui-express: MIT
- *uuid*, https://www.npmjs.com/package/uuid: MIT
- *ws*, https://www.npmjs.com/package/ws: MIT

Frontend "App-Store"

- ...
- ...

Backend "App-Store"

- ...
- ...

Vanilla-Stack

- *Kubernetes*, https://github.com/kubernetes/kubernetes/blob/master/LICENSE: Apache 2.0
- *CloudFoundry*, https://lists.cloudfoundry.org/g/cf-dev/topic/list_of_approved_open_source/13270295: Apache 2.0
- *OpenStack*,https://governance.openstack.org/tc/reference/licensing.html: Apache 2.0
- *OpenShift 3.5 - 4.5*, https://docs.openshift.com/container-platform/4.5/welcome/index.html: Apache 2.0
- *Rook*, https://github.com/rook/rook/blob/master/LICENSE: Apache 2.0
- *Prometheus*, https://prometheus.io/docs/introduction/faq/#what-license-is-prometheus-released-under: Apache 2.0
- *Elastic*, https://www.elastic.co/subscriptions: Apache 2.0
- *FluentD*, https://docs.fluentd.org/#:~:text=%E2%80%8BFluentd%20is%20an%20open,0.: Apache 2.0
- *Grafana*, https://github.com/grafana/grafana/blob/master/LICENSE: Apache 2.0
- *Cri-O*, https://github.com/cri-o/cri-o/blob/master/LICENSE: Apache 2.0

Following this content MIT-License is generally compatible:

https://en.wikipedia.org/wiki/MIT_License#cite_note-26

> The MIT License is a permissive free software license originating at the Massachusetts Institute of Technology (MIT)[5] in the late 1980s.[6] As a permissive license, it puts only very limited restriction on reuse and has, therefore, high license compatibility.[7][8] It is compatible because it can be re-licensed under other licenses. The MIT license is compatible with many copyleft licenses, such as the GNU General Public License (GPL); MIT licensed software can be re-licensed as GPL software, and integrated with other GPL software, but not the other way around.[9]

Following this content 2-clause BSD-License is generally compatible with all FOSS-Licenses:

https://en.wikipedia.org/wiki/BSD_licenses#:~:text=usages%20under%20them.-,FOSS%20compatibility,and%20as%20well%20proprietary%20licenses).

> FOSS compatibility The 3-clause BSD license, like most permissive licenses, is compatible with almost all FOSS licenses (and as well proprietary licenses).[17][18] Two variants of the license, the New BSD License/Modified BSD License (3-clause),[6] and the Simplified BSD License/FreeBSD License (2-clause)[8] have been verified as GPL-compatible free software licenses by the Free Software Foundation, and have been vetted as open source licenses by the Open Source Initiative.[3] The original, 4-clause BSD license has not been accepted as an open source license and, although the original is considered to be a free software license by the FSF, the FSF does not consider it to be compatible with the GPL due to the advertising clause.[2]

*Conclusion:*

If I am understanding right we're targeting with this to Apache 2.0 to not share the whole code of each and everything (expected from GNU GPL3).

Differences between Apache 2.0 and GNU GPL
What is the difference between the Apache License 2.0 and the GNU GPL? The GNU GPL is a copyleft license. So software that uses any GPL-licensed component has to release its full source code and all rights to modify and distribute the entire code. The Apache License 2.0 doesn't impose any such terms.