= VanillaStack

There are multiple Vendor-Stacks out there, that promise to deliver an installation without hazzles, full integration and total flexibility - only to vendor lock you to the tools, frameworks and interfaces of a product.

VanillaStack wants to be and is different: VanillaStack offers the integration of plain upstream projects. VanillaStack will use directly the core components of Kubernetes, OpenStack, Ceph, Rook, Cloudfoundry, Harbor and many more.

This ensures, at any time, to work around or without VanillaStack, because, Vanilla doesn't want to own the stack. Vanilla wants to help but imposes no limits on your tooling.

== The VanillaStack project

VanillaStack understands Kubernetes as the operating system of your datacenter and helps you to setup a seamless installation of core cloud services.
It offers a cloudstack installation of the following OpenSource projects:
* Kubernetes
* Ceph via Rook
* OpenStack
* Cloudfoundry
* Guacamole
* Kubevirt
* ... and more

 ... all including Monitoring and Metrics preconfigured.

The VanillaStack project is licensed under link:LICENSE[Apache 2.0 License].

== CI/CD status
Testing: image:https://gitlab.cloudical.net/vanillastack/vanillastack/badges/testing/pipeline.svg[link="https://gitlab.cloudical.net/vanillastack/vanillastack/-/commits/testing",title="pipeline status"]


== VanillaStack Project Scope & Core Design Goals

Kubernetes First::
VanillaStack understands Kubernetes as its operating system.
All additional components are rolled out within containers.
Always and everwhere.

IaaS. CaaS. PaaS. All included. All working::
VanillaStack is based on the best Container-as-a-Service-platform: Kubernetes.
It allows you to roll out the best Infrastructure-as-a-Service-platform: OpenStack.
It runs the best Platform-as-a-Service-platform: Cloud Foundry.
All from an easy to use installer, all working out-of-the-box.

The best management and operations tools::
With VanillaStack, the most commonly used management and operations tools, are just a click away.
Install Prometheus, Grafana and the EFK-stack with ease.
Enjoy operations.

Commercial and Open-Source ecosystem::
VanillaStack is not a Kubernetes distribution. VanillaStack is an open-source ecosystem.
The core of VanillaStack are a web-based installer and a web-based AppStore.
Open for everyone, be it open-source or commercial offering.
But always quality assured and curated.

Only Open-Source. Only Community-Projects::
VanillaStack is made of open-source projects only.
We use the vanilla community projects.
No vendor lock, no proprietary code, no hidden magic.
Only open-source and only community.

== Vanilla Community Values

Inclusive::
Our ambitions are global. The Vanilla community is, too. The perspectives and skills necessary to achieve our goals are wide and varied; we believe in creating a community and a project that is inclusive, accessible, and welcoming to everyone.
Open::
We are dedicated to remaining open and transparent. We believe in keeping Vanilla Community code freely and fully available to be viewed, modified, and used without vendor lock-in or other in-built limitations.
Inspired::
Vanilla is all about the challenge. Our goals are not small: we want to build the best and simple to use Cloud stack, one that can work with any hardware and interoperate with all workloads. Vanilla is built on hard work, ingenuity, and an engineering mindset. We embrace hard problems and find inspired solutions.
Evolving::
Vanilla is continuously growing and adapting. As a community project, there is no limit to its development. We continuously make room for improvement and welcome the opportunities offered by the ever-evolving nature of community projects.


We are excited about your interest in Vanilla and hope you will join us. We take our community very seriously, and we are committed to creating a community built on respectful interactions and inclusivity

== Requirements
VanillaStack requirements:

* Fedora 32

== Documentation
The dev documentation is stored at: [docs.vanillastack.io]

== Report a Bug
For filing bugs, suggesting improvements, or requesting new features, please open an issue.


== Contact
Please use the following to reach members of the community:

[Discource](https://discourse.vanillastack.io/)

== Contribute
Please read and apply the following rules to contribute to this project:

* One git repository for all automation code (THIS REPOSITORY ONLY!)
* How to contribute to this repository?
  ** Keep it modular - write Ansible roles! each feature should be one role
  ** documentation for
  ** Work with branches
    *** master branch = production branch, used for all production setups
    *** feature branch = personal branches to work on a new feature (based on master branch)
  ** Make it understandable for other persons
    *** Comment your code
    *** Each role needs a description
      *** What is the role doing?
      *** What is required for usage?
    ** Make usefull commits
      *** Use Tags: ADD / NEW / FIX / CHG in front of your commits
      *** Use Comment tag for deeper information at bigger changes
  ** No hardcoding
    *** use variables
    *** variables must be defined outsite of the role (vars, group_vars, host_vars, etc)
  ** New features needs to merged into the master branch by using pull-requests
    *** the code needs to be review and approved by 2 team members
    *** the approvement needs to be documented!
    *** all new features merges needs the documentation part in the merge request!
  ** NEVER commit keys, credentials, usernames, passwords, etc to the git repository!!!
    *** all keys and credentials must be stored in AWX
  ** using shell scripts / bash commands is the last option
    *** only if there is no Ansible module available
    *** single commands can be used by command/shell module
    *** multiline commands needs to be stored in an script
    *** script/bash usage must be documented in detail (why you are using this?)
    *** the Ansible role must be able to handle bash command errors
* Bug handling
  ** For each Bug open an Issue at the gitlab project page
  ** Bugs will be tracked by the project board
* Feature requests
  ** Feature requests can be requestes by creating an Issue
  ** Feature requests will be tracked by the project board
* Playbooks don't execute any tasks, they are used to call roles.
  ** Every Role is used for one part and should include multiple tasks
  ** tasks should not be to complex, f.e. you do not provision a bastion host and install kubernetes on top in one task

=== Cloning the Repository

This project uses git submodules to ensure you get everything needed, please use the following command(s):
[source,console]
----
# For git >= 2.13
git clone --recurse-submodules GIT_REPOSITORY_URL
# For older git versions
git clone GIT_REPOSITORY_URL
cd REPO_NAME
git submodule update --init --recursive
----

=== Workflow
* Create a feature / personal branch based on the master branch
* Change your stuff
* Create a merge request to "testing" branch
* Two Developers / Maintainers needs to review and ACK the changes by +1
* One of the Maintainers merge the branch to "testing"
* Pipeline is starting. If successful the testing branch will be merged to master automatically.
