---
- name: Install Python if not available
  hosts: all
  gather_facts: false
  roles:
    - role: deploy-kubernetes
      action: 00_check_for_python

- name: Create inventory for scaling
  hosts: master[0]
  roles:
    - role: deploy-kubernetes
      action: 00_create_new_inventory

- name: Wait for nodes
  hosts: install_nodes,install_master,master[0]
  become: false
  gather_facts: false
  roles:
    - role: wait-for-nodes

- name: Disable SELinux on RedHat distros
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 01_disable_selinux
      when: ansible_os_family == 'RedHat' and ansible_architecture == "x86_64"

- name: Configure Servers
  hosts: install_nodes,install_master
  become: true
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 01_configure_systems_debian_amd64
      when: ansible_os_family == 'Debian' and ansible_architecture == "x86_64"
    - role: deploy-kubernetes
      action: 01_configure_systems_rhel8_amd64
      when: ansible_os_family == 'RedHat' and ansible_architecture == "x86_64"

- name: Install Loadbalancing
  ansible.builtin.import_playbook: type_install_loadbalancing.yaml

- name: Configure Kube Systems
  hosts: install_nodes,install_master
  become: true
  gather_facts: false
  roles:
    - role: deploy-kubernetes
      action: 02_configure_cluster

- name: Init Kubernetes Cluster
  hosts: install_master[0]
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 03_deploy_kubernetes

- name: generate secrets
  hosts: master[0]
  gather_facts: false
  roles:
    - role: deploy-kubernetes
      action: 02-1_generate-certificate

- name: Add Master to Kubernetes Cluster
  hosts: install_master[1:]
  become: true
  gather_facts: false
  roles:
    - role: deploy-kubernetes
      action: 04_add_nodes

- name: Add worker to Kubernetes Cluster
  hosts: install_nodes
  become: true
  gather_facts: false
  roles:
    - role: deploy-kubernetes
      action: 05_add_worker

- name: Create folder for config
  hosts: localhost
  vars:
    ansible_connection: local
  tasks:
    - name: Make sure local uuid directory exists
      file:
        state: directory
        path: "/tmp/ansible/{{ cluster_uuid }}"
        recurse: true

- name: Gather facts
  hosts: master,worker
  become: false
  gather_facts: true

- name: Deploy Networking
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
    - role: deploy-kubernetes
      action: "06_configure_network_{{cluster_sdn|default('cilium')}}"

- name: Label Nodes
  hosts: master[0]
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 07_label_nodes
