---
- name: install stratos
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
    - role: install-stratos

- name: install redis cluster
  hosts: master[0]
  gather_facts: false
  roles:
    - role: install-redis-cluster
    - role: install-redis
