---
- name: reset kubernetes cluster
  hosts: master,worker
  become: true
  gather_facts: no
  roles:
    - role: reset-cluster
      action: reset-kubernetes
    - role: reset-cluster
      action: remove-local-files
        
- name: reset osds
  hosts: storage
  become: true
  gather_facts: no
  roles:
    - role: reset-cluster
      action: reset-ceph

- name: remove stored files
  hosts: localhost
  connection: local
  become: true
  gather_facts: no
  roles:
    - role: reset-cluster
      action: remove-local-files
