---
- name: reset kubernetes cluster
  hosts: master,worker
  become: true
  gather_facts: false
  roles:
    - role: reset-cluster
      action: reset-kubernetes
      when: reset_environment
    - role: reset-cluster
      action: remove-local-files
      when: reset_environment
        
- name: reset osds
  hosts: storage
  become: true
  gather_facts: false
  roles:
    - role: reset-cluster
      action: reset-ceph
      when: reset_environment

- name: remove stored files
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  roles:
    - role: reset-cluster
      action: remove-local-files
      when: reset_environment
