---
- name: Deploy Velero CLI
  hosts: master[0]
  become: true
  gather_facts: no
  roles:
    - role: install-velero
      action: cli
      when: velero.enabled

- name: Deploy Velero server
  hosts: master[0]
  become: false
  gather_facts: no
  roles:
    - role: install-velero
      action: velero
      when: velero.enabled
