---
- name: install galaxy collection
  hosts: localhost
  connection: local
  tasks:
  - command: ansible-galaxy collection install community.kubernetes
  - command: ansible-galaxy collection install community.general
  - command: pwd
  - name: install pip dependencies
    pip:
      requirements: "{{ lookup('env', 'PWD') }}/requirements.txt"
