---
- name: Deploy KubeVirt
  hosts: master[0]
  become: false
  gather_facts: false
  roles:
    - role: deploy-kubevirt
      action: operator
      when: vanillaservices.kubevirt_enabled

- name: Deploy KubeVirt CLI
  hosts: master[0]
  become: true
  gather_facts: false
  roles:
    - role: deploy-kubevirt
      action: virtctl
      when: vanillaservices.kubevirt_enabled
