---
- name: Install Python if not available
  hosts: all
  gather_facts: false
  roles:
    - role: deploy-kubernetes
      action: 00_check_for_python

- name: Create inventory for scaling
  hosts: master[0]
  roles:
    - role: deploy-kubernetes
      action: 00_create_new_inventory

- name: Wait for nodes
  hosts: install_nodes,install_master,master[0]
  become: false
  gather_facts: false
  roles:
    - role: wait-for-nodes

- name: Secure Servers (Installing Polyverse)
  hosts: install_nodes,install_master
  become: true
  gather_facts: true
  roles:
    - role: deploy-polyverse
      when: polyverse.enabled

- name: Disable SELinux on RedHat distros
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 01_disable_selinux
      when: ansible_distribution == 'RedHat' and ansible_architecture == "x86_64"

- name: Configure Servers
  hosts: install_nodes,install_master
  become: true
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 01_configure_systems_debian_amd64
      when: ansible_distribution == 'Debian' and ansible_architecture == "x86_64"
    - role: deploy-kubernetes
      action: 01_configure_systems_rhel8_amd64
      when: ansible_distribution == 'RedHat' and ansible_architecture == "x86_64"

- name: Install Loadbalancing
  ansible.builtin.import_playbook: type_install_loadbalancing.yaml

- name: Configure Kube Systems
  hosts: install_nodes,install_master
  become: true
  gather_facts: false
  roles:
    - role: deploy-kubernetes
      action: 02_configure_cluster

- name: Init Kubernetes Cluster
  hosts: install_master[0]
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 03_deploy_kubernetes

- name: Generate Secrets
  hosts: master[0]
  gather_facts: false
  roles:
    - role: deploy-kubernetes
      action: 02-1_generate-certificate

- name: Add Master to Kubernetes Cluster
  hosts: install_master[1:]
  become: true
  gather_facts: false
  roles:
    - role: deploy-kubernetes
      action: 04_add_nodes

- name: Add worker to Kubernetes Cluster
  hosts: install_nodes
  become: true
  gather_facts: false
  roles:
    - role: deploy-kubernetes
      action: 05_add_worker

- name: Create folder for config
  hosts: localhost
  vars:
    ansible_connection: local
  tasks:
    - name: Make sure local uuid directory exists
      ansible.builtin.file:
        state: directory
        path: "/tmp/ansible/{{ cluster_uuid }}"
        recurse: true

- name: Gather facts
  hosts: master,worker
  become: false
  gather_facts: true

- name: Deploy Networking
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
    - role: deploy-kubernetes
      action: "06_configure_network_{{cluster_sdn|default('cilium')}}"

- name: Label Nodes
  hosts: master[0]
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 07_label_nodes

- name: Install Metrics Server
  hosts: master[0]
  become: false
  gather_facts: true
  roles:
    - role: deploy-metrics-server
      when: vanillaservices.metricsServer_enabled

- name: Deploy Ingress Nginx
  hosts: master[0]
  become: false
  gather_facts: false
  roles:
    - role: prepare-registry
      when: ingress.enabled
    - role: deploy-ingress-nginx
      when: ingress.enabled

- name: Deploy Rook
  hosts: master[0]
  become: false
  gather_facts: false
  roles:
    - role: prepare-registry
    - role: deploy-rook
      when: vanillastorageprovider == "rook"

- name: Deploy localprovisioner
  hosts: master[0]
  become: false
  gather_facts: false
  roles:
    - role: deploy-localpath-provsioner
      when: localprovisioner.enabled

- name: Deploy Cert Manager
  hosts: master[0]
  become: false
  gather_facts: true
  roles:
    - role: prepare-registry
      when: certmanager.enabled
    - role: deploy-certmanager
      when: certmanager.enabled

- name: Deploy Postgres Operator
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: vanillaservices.pgOperator_enabled
    - role: deploy-postgres-operator
      when: vanillaservices.pgOperator_enabled

- name: Deploy Keycloak
  hosts: master[0]
  become: false
  gather_facts: false
  roles:
    - role: deploy-keycloak
      when: vanillaservices.keycloak_enabled

- name: Install K8S Dashboard
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: vanillaservices.dashboard_enabled
    - role: install-kubedashboard
      when: vanillaservices.dashboard_enabled

- name: Deploy Harbor
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: vanillaservices.harbor_enabled
    - role: deploy-harbor
      when: vanillaservices.harbor_enabled

