---
- name: install redis cluster
  hosts: master[0]
  gather_facts: false
  roles:
    - role: install-redis-cluster
      when: redis.cluster

- name: install redis sentinel
  hosts: master[0]
  gather_facts: false
  roles:
    - role: install-redis-sentinel
      when: not redis.cluster and redis.sentinel
