---
- name: Setup Installation Node (localhost)
  hosts: localhost
  connection: local
  tasks:
  - name: Install collections from Ansible galaxy
    command: "ansible-galaxy collection install {{ item }}"
    loop:
      - community.kubernetes
      - community.general
  - name: Install pip dependencies
    pip:
      requirements: "{{ playbook_dir }}/requirements.txt"
