---
- name: Uninstall rook-ceph resources
  hosts: master[0]
  gather_facts: false
  roles:
    - role: reset-cluster
      action: uninstall-ceph
      when: reset_environment

- name: Reset kubernetes cluster
  hosts: master,worker
  become: true
  gather_facts: true
  roles:
    - role: reset-cluster
      action: reset-node
      when: reset_environment
    - role: reset-cluster
      action: remove-local-files
      when: reset_environment

- name: Reset OSDs
  hosts: storage
  become: true
  gather_facts: false
  roles:
    - role: reset-cluster
      action: reset-ceph
      when: reset_environment
