---
- name: install nextcloud
  hosts: master[0]
  gather_facts: true
  tasks:
  - name: deploy Calico for ppc64le
    debug:
      var: hostvars[item].ansible_architecture
    loop: "{{ groups.master }}"
      #  - name: get nextcloud container
      #    community.kubernetes.k8s_info:
      #      kind: Pod
      #      namespace: "{{ nextcloud_instancename }}"
      #      label_selectors:
      #        - "app.kubernetes.io/component = app"
      #        - "app.kubernetes.io/name = {{ nextcloud_instancename }}"
      #    register: nextcloud_container
      #  
      #  - debug:
      #      var: nextcloud_container.resources | json_query('[].metadata.name') | join(',')
      #  - name: configure collabora
      #    command: "kubectl exec -n {{ nextcloud_instancename }} {{ nextcloud_container.resources | json_query('[].metadata.name') | join(',') }} -c nextcloud -- {{ item }}"
      #    loop:
      #      - su www-data -s /bin/bash -c "/var/www/html/occ app:install richdocuments"
      #      - su www-data -s /bin/bash -c "/var/www/html/occ config:app:set --value https://{{ nextcloud.collabora.ingress.publicDomain }} richdocuments wopi_url"
      #      - su www-data -s /bin/bash -c "/var/www/html/occ config:app:set --value yes richdocuments disable_certificate_verification"
      #      - su www-data -s /bin/bash -c "/var/www/html/occ richdocuments:activate-config"
