---
- name: Install UAA
  community.kubernetes.helm:
    chart_ref: vanillastack/uaa
    chart_version: "{{ stratos.uaa.version }}"
    name: uaa
    release_namespace: stratos
    create_namespace: true
    values: "{{ lookup('template', 'uaa-values.yaml.j2') | from_yaml }}"
    wait: true

- name: Deploy UAA client
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template','uaaclient.yaml.j2')}}"
    wait: yes

- name: get admin token
  shell: echo "$(kubectl get secret -n stratos -o json secrets|jq -r '.data.uaa-admin-client-secret')"|base64 -d
  register: uaacttoken

- name: set target
  command: "kubectl exec -ti $(kubectl get po -n stratos -l app=uaaclient |grep uaaclient|cut -d' ' -f1) -n stratos -- uaac target uaa.{{ clusterTLDomain }} --skip-ssl-validation"
  ignore_errors: true

- name: uaac login
  command: "kubectl exec -ti $(kubectl get po -n stratos -l app=uaaclient |grep uaaclient|cut -d' ' -f1) -n stratos -- uaac token client get admin -s {{uaactoken.stdout}}"
  ignore_errors: true

- name: uaac add client
  command: "kubectl exec -ti $(kubectl get po -n stratos -l app=uaaclient |grep uaaclient|cut -d' ' -f1) -n stratos -- uaac client add {{stratos.coreDomain}} --name {{stratos.coreDomain}} --scope network.admin,network.write,cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write,doppler.firehose,uaa.user,routing.router_groups.read,routing.router_groups.write,cloud_controller.admin_read_only,cloud_controller.global_auditor,perm.admin,clients.read --authorized_grant_types authorization_code,refresh_token --authorities uaa.admin --access_token_validity 600 --refresh_token_validity 2592000 --autoapprove true --redirect_uri https://{{stratos.coreDomain}}/pp/v1/auth/sso_login_callback -s {{stratos.clientSecret}}"
  ignore_errors: true
 
- name: Install stratos
  community.kubernetes.helm:
    chart_ref: vanillastack/console
    chart_version: "{{ stratos.version }}"
    name: console
    release_namespace: stratos
    values: "{{ lookup('template', 'stratos-values.yaml.j2') | from_yaml }}"
    wait: true
