---
- name: Install UAA
  community.kubernetes.helm:
    chart_ref: vanillastack/uaa
    chart_version: "{{ stratos.uaa.version }}"
    name: uaa
    release_namespace: stratos
    create_namespace: true
    values: "{{ lookup('template', 'uaa-values.yaml.j2') | from_yaml }}"
    wait: true

- name: Deploy UAA client
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template','uaaclient.yaml.j2')}}"
    wait: yes

- name: get admin token
  shell: echo "$(kubectl get secret -n stratos -o jsonpath="{.data.uaa-admin-client-secret}" secrets)"|base64 -d
  register: uaactoken

- name: get uaaclient pod
  shell: "kubectl get po -n stratos -l app=uaaclient |grep uaaclient|cut -d' ' -f1"
  register: uaapod

- name: set target
  shell: "kubectl exec -ti {{uaapod.stdout}} -n stratos -- /registerclient.sh '{{uaactoken.stdout}}' '{{stratos.coreDomain}}' '{{stratos.clientSecret}}' 'uaa.{{ clusterTLDomain }}'"
  ignore_errors: true

- name: Install stratos
  community.kubernetes.helm:
    chart_ref: vanillastack/console
    chart_version: "{{ stratos.version }}"
    name: console
    release_namespace: stratos
    values: "{{ lookup('template', 'stratos-values.yaml.j2') | from_yaml }}"
    wait: true
