---
openstack:
  enabled: false
  namespace: openstack
  publicDomain: "{{ kubernetes.loadBalancer.clusterDomain }}"
  publicProto: "http"
  region: RegionOne
  # releases available:
  # - train
  # - ussuri (not tested)
  release: "stein"
  tls:
    enabled: true
    useCertManager: true
    letsEncrypt:
      enabled: true
  mariadb:
    enabled: true
    chartName: mariadb
    chartVersion: 0.1.0
    createService: false
    replicas: 3
    persistence:
      enabled: true
      storageClass: "rook-ceph-block"
      diskSize: 30Gi
    auth:
      admin:
        password: ""
      sst:
        password: ""
      audit:
        password: ""
      exporter:
        password: ""
  rabbitmq:
    enabled: true
    chartName: rabbitmq
    chartVersion: 0.1.0
    createService: false
    replicas: 2
    persistence:
      enabled: true
      storageClass: "rook-ceph-block"
      diskSize: 20Gi
    auth:
      admin:
        password: ""
  memcached:
    enabled: true
    chartName: memcached
    chartVersion: 0.1.0
    createService: false
    replicas: 1
  ceph:
    enabled: true
    rook:
      namespace: "rook-ceph"
      fsid: "602a7124-e4ba-43fd-a6f7-00bd574329d8"
  barbican:
    enabled: true
    chartName: barbican
    chartVersion: 20200903
    createService: true
    api:
      replicas: 2
    endpoints:
      publicURLPrefix: "barbican"
    auth:
      service:
        password: ""
      db:
        password: ""
      messaging:
        password: ""
  cinder:
    enabled: true
    chartName: cinder
    chartVersion: 20200903
    createService: true
    rbd:
      enabled: true
      rbdPool: cinder.volumes
      rbdUser: cinder
      rbdBackupUser: cinder-backup
      rbdBackupPool: cinder.backups
    api:
      replicas: 2
      v1Enabled: false
    volume:
      replicas: 1
      osapiVolumeWorkers: 1
    scheduler:
      replicas: 1
    backup:
      enabled: false
      replicas: 1
    endpoints:
      publicURLPrefix: "cinder"
    auth:
      service:
        password: ""
      db:
        password: ""
      messaging:
        password: ""
      cinderTest:
        password: ""
  congress:
    enabled: false
    chartName: congress
    chartVersion: 20200903
    createService: true
    api:
      replicas: 2
    policyEngine:
      replicas: 2
    datasource:
      replicas: 1
  designate:
    enabled: false
    chartName: designate
    chartVersion: 20200903
    createService: true
    auth:
      service:
        password: ""
  glance:
    enabled: true
    chartName: glance
    chartVersion: 20200903
    createService: true
    defaultBackend: rbd
    rbd:
      enabled: true
      cephAppName: glance
      rbdPool: glance.images
      rbdUser: glance
      showImageDirectUrl: true
    api:
      replicas: 2
      v1Enabled: false
      version: 2
    registry:
      replicas: 2
      v2Enabled: true
    endpoints:
      publicURLPrefix: "glance"
    auth:
      service:
        password: ""
      db:
        password: ""
      messaging:
        password: ""
      glanceTest:
        password: ""
      radosgw:
        password: ""
  heat:
    enabled: true
    chartName: heat
    chartVersion: 20200903
    createService: true
    api:
      replicas: 2
    cfn:
      replicas: 2
    cloudwatch:
      replicas: 2
    engine:
      replicas: 2
    endpoints:
      publicURLPrefix: "heat"
      cfnPublicURLPrefix: "heat-cfn"
    auth:
      service:
        password: ""
      db:
        password: ""
      messaging:
        password: ""
      heatTest:
        password: ""
      heatDomain:
        password: ""
      serviceTrustee:
        password: ""
  horizon:
    enabled: true
    chartName: horizon
    chartVersion: 20200903
    createService: true
    replicas: 2
    endpoints:
      useDirectPublicDomain: false
      publicURLPrefix: "horizon"
    auth:
      db:
        password: ""
  ironic:
    enabled: false
    chartName: ironic
    chartVersion: 20200903
    createService: true
    auth:
      service:
        password: ""
  keystone:
    enabled: true
    chartName: keystone
    chartVersion: 20200903
    createService: true
    endpoints:
      publicURLPrefix: "keystone"
    api:
      replicas: 2
    auth:
      admin:
        password: ""
      keystoneTest:
        password: ""
      db:
        password: ""
      messaging:
        password: ""
  libvirt:
    enabled: true
    chartName: libvirt
    chartVersion: 0.1.0
    createService: false
  mistral:
    enabled: true
    chartName: mistral
    chartVersion: 20200903
    createService: true
    api:
      replicas: 2
    engine:
      replicas: 2
    eventEngine:
      replicas: 2
    executor:
      replicas: 2
    endpoints:
      publicURLPrefix: "mistral"
    auth:
      service:
        password: ""
      mistralTest:
        password: ""
      db:
        password: ""
      messaging:
        password: ""
  neutron:
    enabled: true
    chartName: neutron
    chartVersion: 20200913
    createService: true
    extInterface: "enp3s0"
    tunnelInterface: "enp2s0"
    server:
      replicas: 2
    l3:
      ha: false
      maxAgentsPerRouter: 1
      haNetworkType: vxlan
      dhcpAgents: 2
    endpoints:
      publicURLPrefix: "neutron"
    auth:
      service:
        password: ""
      db:
        password: ""
      messaging:
        password: ""
      neutronTest:
        password: ""
  nova:
    enabled: true
    chartName: nova
    chartVersion: 20200903
    createService: true
    apiMetadata:
      replicas: 1
    placement:
      replicas: 2
    osapi:
      replicas: 2
    conductor:
      replicas: 2
    consoleauth:
      replicas: 2
    scheduler:
      replicas: 1
    novncproxy:
      replicas: 1
    endpoints:
      publicURLPrefix: "nova"
      novncURLPrefix: "novnc"
      placementURLPrefix: "placement"
    libvirt:
      # bare metal = kvm, VMs = qemu
      virtType: kvm
      # bare metal = host-passthrough or host-model, vm= none
      cpuMode: host-model
    auth:
      service:
        password: ""
      db:
        password: ""
      placement:
        password: ""
      messaging:
        password: ""
      novaTest:
        password: ""
  octavia:
    enabled: false
    chartName: octavia
    chartVersion: 20200903
    createService: true
    api:
      replicas: 2
    worker:
      replicas: 1
    housekeeping:
      replicas: 1
    endpoints:
      publicURLPrefix: "octavia"
    auth:
      service:
        password: ""
      db:
        password: ""
      messaging:
        password: ""
      octaviaTest:
        password: ""
  openvswitch:
    enabled: true
    chartName: openvswitch
    chartVersion: 0.1.0
    createService: false
  radosgw:
    enabled: false
    chartName: ceph-rgw
    chartVersion: 0.1.0
    createService: true
    endpoints:
      publicURLPrefix: "radosgw"
    auth:
      service:
        password: ""
  senlin:
    enabled: true
    chartName: senlin
    chartVersion: 20200903
    createService: true
    api:
      replicas: 2
    engine:
      replicas: 2
    endpoints:
      publicURLPrefix: "senlin"
    auth:
      service:
        password: ""
      db:
        password: ""
      messaging:
        password: ""
      senlinTest:
        password: ""
