---

- set_fact:
    collabora_server_name: "{{ nextcloud.collabora.ingress.publicDomain | replace('.', '\\.') }}"
    nextcloud_collabora_domain: "{{ nextcloud.ingress.publicDomain | replace('.', '\\\\.') }}"

- name: create file
  template:
    src: "collabora.yaml.j2"
    dest: "/tmp/collabroa.yaml"

- name: Install collabora
  community.kubernetes.k8s:
    state: present
    template: "collabora.yaml.j2"
