---
- name: Install cpupower
  package:
    name: 'linux-cpupower'
    state: present

- name: Delete old cpupower governor service
  file:
    path: /etc/systemd/system/cpupower-govenor.service
    state: absent
  notify:
    - systemd reload

- name: Create cpupower set governor service
  template:
    src: etc/systemd/system/cpupower-governor.service
    dest: /etc/systemd/system/cpupower-governor.service
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd reload
    - restart cpupower governor service

- name: Enable cpupower governor service
  systemd:
    name: cpupower-governor
    enabled: yes
