= live_image

This is the directory, responsible for building the live-image for the installer.

The live image is an ISO image that can be booted directly via CDROM, USB or any other way you please.


== Technology

* Debian as a base Image
* live-build as build-chain
* Installer itself will be running as docker container
* Visual Frontend via Running Desktop-Environment with a Webbrowser

== Building

For Development there are two modes how to build:

* via gitlab-ci
* locally via docker

The scripts are split in a way, that they function as well locally as also in a gitlab-ci pipeline

For local building, we use docker to get the a defined debian:buster installation as base. In gitlab we are already running in a debian:buster container, so steps differ a bit.

=== local building with docker

The Dockerfile mainly just consists of preparing a build-environment for live-build:
- copying the rootfs/ directory into the container-root
- calling `prepare-installer.bash`

Build the container:

  docker build -t vanilla-installa .

After you build that simple container you can run it with:

  `docker run -ti --name vanilla -v <OUTPUTPATH>/data:rw --privileged anilla-installa`

In the container, you can then start `./build-installer.bash`. At the end, the build-artifacts will be copied to `/data` where you should mount your output-directory to.

Note: The interactive part is currently implemented because of the development-phase for troubleshooting. Sooner or later this will change to an headless call to directly call the `build-installer.bash` script.

=== building via gitlab-ci-pipeline

Because, we are already running in a fitting docker container, there is no need to rebuild. We just need to adjust the living room.

So its just a matter of copying the files around and calling `prepare-installer.bash` directly followed by `build-installer.bash`

Artifacts will be stored in the defined `OUTPUT` directory
