---
- name: Create Grafana namespace
  kubernetes.core.k8s:
    name: "{{grafana.namespace}}"
    kind: Namespace
    state: present

- name: Install Grafana
  kubernetes.core.helm:
    name: grafana
    chart_ref: vanillastack/grafana
    release_namespace: "{{ grafana.namespace }}"
    values: "{{ lookup('template', 'grafana_values.yaml.j2') | from_yaml }}"
    chart_version: "{{ grafana.chartVersion }}"

- name: Deploy Keycloak client
  include_tasks: create-client.yml
  when: vanillaservices.keycloak_enabled
