---
- name: Deploy Rook
  include_tasks: deploy.yaml
  when: rook.enabled
  with_items:
    - { name: common, wait: false, delay: 0}
    - { name: operator, wait: false, delay: 10}
    - { name: cluster, wait: false, delay: 10}
    - { name: toolbox, wait: false, delay: 0}
    - { name: objectStorage, wait: false, delay: 0}
    - { name: filesystem, wait: false, delay: 0}
    - { name: storageClassRBD, wait: false, delay: 0}
    - { name: storageClassObject, wait: false, delay: 0}
    - { name: storageClassFile, wait: false, delay: 0}

- name: Delay for upcoming Rook
  wait_for:
    timeout: 60
  when: rook.enabled

- name: wait for CephCluster to come up
  shell: kubectl get cephcluster "{{rook.cluster.name}}" -o json -n "{{rook.namespace}}"|egrep "(HEALTH_OK|HEALTH_WARN)"
  register: cephcluster
  until: cephcluster.rc==0
  retries: 120
  delay: 10
  when: rook.enabled
