---
- name: Create rook-ceph Namespace
  kubernetes.core.k8s:
    name: "{{ rook.namespace }}"
    kind: Namespace
    state: present

- name: Install Rook Operator
  kubernetes.core.helm:
    name: rook-ceph
    chart_ref: vanillastack/rook-ceph
    release_namespace: "{{ rook.namespace }}"
    values: "{{ lookup('template', 'operator-values.yaml.j2') | from_yaml }}"
    chart_version: "{{ rook.chartVersion }}"

- name: Install Ceph Cluster
  kubernetes.core.helm:
    name: rook-ceph-cluster
    chart_ref: vanillastack/rook-ceph-cluster
    release_namespace: "{{ rook.namespace }}"
    values: "{{ lookup('template', 'ceph-cluster-values.yaml.j2') | from_yaml }}"
    chart_version: "{{ rook.chartVersion }}"

- name: Wait for CephCluster to come up
  ansible.builtin.shell: kubectl get cephcluster "{{ rook.cluster.name }}" -o json -n "{{ rook.namespace }}"|egrep "(HEALTH_OK|HEALTH_WARN)"
  register: cephcluster
  until: cephcluster.rc==0
  retries: 120
  delay: 10
  when: rook.enabled

- name: Sleep 5 Minutes for letting rook be stable
  ansible.builtin.pause:
    minutes: 5
