---
- name: Deploy Rook
  include_tasks: deploy.yaml
  when: rook.enabled
  with_items:
    - { name: crds, wait: false, delay: 10}
    - { name: common, wait: false, delay: 0}
    - { name: operator, wait: false, delay: 10}
    - { name: cluster, wait: false, delay: 10}
    - { name: toolbox, wait: false, delay: 0}
    - { name: objectStorage, wait: false, delay: 0}
    - { name: filesystem, wait: false, delay: 0}
    - { name: storageClassRBD, wait: false, delay: 0}
    - { name: storageClassObject, wait: false, delay: 0}
    - { name: storageClassFile, wait: false, delay: 0}
    - { name: dashboard, wait: false, delay: 0}

- name: Deploy Rook monitoring
  when: rook.cluster.monitoring.enabled
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template','{{item}}')}}"
  with_items:
    - rbac.yaml.j2
    - csi-metrics-service-monitor.yaml.j2
    - service-monitor.yaml.j2

- name: Deploy Rook monitoring
  when: rook.cluster.monitoring.enabled
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file','{{item}}')}}"
  with_items:
    - prometheus-ceph-v14-rules.yaml

- name: Delay for upcoming Rook
  wait_for:
    timeout: 60
  when: rook.enabled

- name: wait for CephCluster to come up
  shell: kubectl get cephcluster "{{rook.cluster.name}}" -o json -n "{{rook.namespace}}"|egrep "(HEALTH_OK|HEALTH_WARN)"
  register: cephcluster
  until: cephcluster.rc==0
  retries: 120
  delay: 10
  when: rook.enabled

- name: Sleep 5 Minutes for letting rook be stable 
  pause:
    minutes: 5