export default Object.freeze({
    Event_AcceptedTermsChanged: "Event_AcceptedTermsChanged",
    Event_MastersCountChanged: "Event_MastersCountChanged",
    Event_WorkersCountChanged: "Event_WorkersCountChanged",
    Event_InstallationKindChanged: "Event_InstallationKindChanged",
    Event_CopiedKeyToNodes: "Event_CopiedKeyToNodes",
    Event_GoBack: "Event_GoBack",
    Event_GoNext: "Event_GoNext",
    Event_NewViewLoaded: "Event_NewViewLoaded",
    Event_NavigationUpdated: "Event_NavigationUpdated",
    Event_InstallationRookUpdated: "Event_InstallationRookUpdated",
    Event_InstallationCFUpdated: "Event_InstallationCFUpdated",
    Event_InstallationOpenStackUpdated: "Event_InstallationOpenStackUpdated",
    Event_PrepareNavigation: "Event_PrepareNavigation",

    Store_UpdateTermsAccepted: "updateTermsAccepted",
    Store_UpdateMasters: "updateMasters",
    Store_UpdateWorkers: "updateWorkers",
    Store_UpdateInstallationKind: "updateInstallationKind",
    Store_UpdateCopiedKeyToNodes: "updateCopiedKeyToNodes",
    Store_LoadedSSHKey: "loadedSSHKey",
    Store_UpdateNavigation: "updateNavigation",
    Store_UpdateGlobalNavigation: "updateGlobalNavigation",
    Store_UpdateInstallationRook: "updateInstallationRook",
    Store_UpdateInstallationCF: "updateInstallationCF",
    Store_UpdateInstallationOpenStack: "updateInstallationOpenStack",
  })
  