export default Object.freeze({
    Event_AcceptedTermsChanged: "Event_AcceptedTermsChanged",
    Event_MastersCountChanged: "Event_MastersCountChanged",
    Event_WorkersCountChanged: "Event_WorkersCountChanged",
    Event_InstallationKindChanged: "Event_InstallationKindChanged",
    Event_CopiedKeyToNodes: "Event_CopiedKeyToNodes",
    Event_GoBack: "Event_GoBack",
    Event_GoNext: "Event_GoNext",
    Event_NewViewLoaded: "Event_NewViewLoaded",
    Event_NavigationUpdated: "Event_NavigationUpdated",
    Event_InstallationRookUpdated: "Event_InstallationRookUpdated",
    Event_InstallationCFUpdated: "Event_InstallationCFUpdated",
    Event_InstallationOpenStackUpdated: "Event_InstallationOpenStackUpdated",
    Event_PrepareNavigation: "Event_PrepareNavigation",
    Event_IpAddressesUpdated: "Event_IpAddressesUpdated",
    Event_OpenStackUpdatedData : "Event_OpenStackUpdatedData",
    Event_CloudFoundryUpdatedData: "Event_CloudFoundryUpdatedData",
    Event_BaseDataUpdated: "Event_InfoDataUpdated",

    Store_UpdateTermsAccepted: "updateTermsAccepted",
    Store_UpdateMasters: "updateMasters",
    Store_UpdateWorkers: "updateWorkers",
    Store_UpdateInstallationKind: "updateInstallationKind",
    Store_UpdateCopiedKeyToNodes: "updateCopiedKeyToNodes",
    Store_LoadedSSHKey: "loadedSSHKey",
    Store_UpdateNavigation: "updateNavigation",
    Store_UpdateGlobalNavigation: "updateGlobalNavigation",
    Store_UpdateInstallationRook: "updateInstallationRook",
    Store_UpdateInstallationCF: "updateInstallationCF",
    Store_UpdateInstallationOpenStack: "updateInstallationOpenStack",
    Store_UpdateIPAddresses: "updateIPAddresses",
    Store_OpenStackUpdateData : "openStackUpdateData",
    Store_CloudFoundryUpdateData: "cloudFoundryUpdateData",
    Store_BaseDataUpdateData: "baseDataUpdateData",

    Network_LoadedInfo: "Network_LoadedInfo",
    Network_CheckingNodes: "Network_CheckingNodes",
    Network_WS_Response: "Network_WS_Response",

    Validate_IpAddress: /^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/,
  })
  