---
- name: Create namespace
  kubernetes.core.k8s:
    name: local-path-storage
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy localpath provisioner
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item ~ '.yaml.j2') | from_yaml }}"
  loop:
    - serviceaccount
    - clusterrole
    - clusterrolebinding
    - configmap
    - deployment
    - storageclass
