---
- name: Remove old installation files
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - cluster_vars.yml
    - ansible

- name: Remove kubeconfig
  file:
    path: ".kube"
    state: absent

- name: Remove old kubelet file
  file:
    path: "/etc/default/kubelet"
    state: absent
