---
- name: Reset the Kubernetes cluster using kubeadm
  ansible.builtin.command: kubeadm reset --force
  ignore_errors: true

- name: Remove Packages
  ansible.builtin.package:
    name:
      - "haproxy"
      - "keepalived"
      - "kubelet"
      - "kubeadm"
      - "kubectl"
      - "cri-o"
      - "runc"
      - "cri-o-runc"
    state: absent
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: Remove Kubernetes dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - /var/lib/kubernetes
