---
# tasks file for reset-kubernetes
- name: Reset  the cluster if set
  command: kubeadm reset --force
  ignore_errors: true

- name: remove Packages
  apt:
    pkg:
      - "kubelet"
      - "kubeadm"
      - "kubectl"
      - "cri-o"
      - "runc"
      - "cri-o-runc"
    update_cache: yes
    purge: true
    state: absent
    force: true
    autoremove: true
    autoclean: true
  register: result
  until: result is not failed
  retries: 10
  delay: 10

