---
- name: Get list of Ceph storage devices
  ansible.builtin.shell: "sudo blkid | grep ceph | awk '{print $1}' | sed 's/://g'"
  register: ceph_storage_devices
  
- name: Reset the Kubernetes cluster using kubeadm
  ansible.builtin.command: kubeadm reset --force
  ignore_errors: true

- name: Unhold packages
  when: ansible_os_family == 'Debian' and ansible_architecture == "x86_64"
  ansible.builtin.command: "apt-mark unhold {{ item }}"
  with_items:
    - "kubelet"
    - "kubeadm"
    - "kubectl"
    - "cri-o"
    - "cri-o-runc"

- name: Remove Packages
  ansible.builtin.package:
    name:
      - "haproxy"
      - "keepalived"
      - "kubelet"
      - "kubeadm"
      - "kubectl"
      - "cri-o"
      - "runc"
      - "cri-o-runc"
    state: absent
  register: result
  until: result is not failed
  retries: 10
  delay: 10
  when: not offline_install

- name: Remove Kubernetes dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - /var/lib/kubernetes
