---
- name: Reset the Kubernetes cluster using kubeadm
  command: kubeadm reset --force
  ignore_errors: true

- name: Remove Packages
  apt:
    pkg:
      - "haproxy"
      - "keepalived"
      - "kubelet"
      - "kubeadm"
      - "kubectl"
      - "cri-o"
      - "runc"
      - "cri-o-runc"
    state: absent
    autoremove: true
    force: true
  register: result
  until: result is not failed
  retries: 10
  delay: 10

- name: Remove Kubernetes dirs
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - /var/lib/kubernetes
