---
- name: Wipe Ceph storage disks on storage nodes
  block:
    - name: Clean hdds with dd
      ansible.builtin.command: "sudo dd if=/dev/zero of={{ item }} bs=1M count=100 oflag=direct,dsync"
      loop: "{{ ceph_storage_devices.stdout_lines }}"
      notify: reboot node
    - name: Zap the disk to a fresh, usable state
      ansible.builtin.command: "sudo sgdisk --zap-all {{ item }}"
      loop: "{{ ceph_storage_devices.stdout_lines }}"
      notify: reboot node
    - name: Destroy information
      ansible.builtin.command: "sudo wipefs -fa {{ item }}"
      loop: "{{ ceph_storage_devices.stdout_lines }}"
      notify: reboot node
    - name: Discard the content of sectors
      ansible.builtin.command: "sudo blkdiscard {{ item }}"
      loop: "{{ ceph_storage_devices.stdout_lines }}"
      notify: reboot node

- name: Make sure rook's data dir HostPath is gone
  ansible.builtin.file:
    path: /var/lib/rook
    state: absent
  notify: reboot node
