---
- name: "{{item.name}} | test public url"
  uri:
    url: "{{openstack.publicProto}}://{{openstack[item.name]['publicURLPrefix'].{{openstackDomain}}"
  when: openstack[item.name]['enabled'] and item.name is not search('horizon')

- name: "{{item.name}} | test public url"
  uri:
    url: "{{openstack.publicProto}}://{{openstackDomain}}"
  when: openstack[item.name]['enabled'] and item.name is search('horizon')
