velero:
  enabled: false
  version: v1.11.0
  chartVersion: 4.0.3
  namespace: velero
  backend: minio # aws|minio (aws for external Backups via S3, minio for internal Backups using PVC)
  resources:
    requests:
      cpu: "1000m"
      memory: "3Gi"
    limits:
      cpu: "1000m"
      memory: "6Gi"
  nodeagent:
    resources:
      requests:
        cpu: "125m"
        memory: "3Gi"
      limits:
        cpu: "1000m"
        memory: "5Gi"
  aws: {}
  #  bucketName: YOUR_BUCKET_NAME
  #  snapshotBucketName: YOUR_SNAPSHOT_BUCKET_NAME
  #  region: "us-east-1"
  #  s3ForcePathStyle: false
  #  publicURL: https://s3.example.com
  #  s3URL: https://s3.example.com
  #  accessKey: YOUR_ACCESS_KEY
  #  secretKey: YOUR_SECRET_KEY
  minio:
    enabled: true
    chartVersion: 5.0.9
    nfs:
      size: 50Gi
      server: example.com
      path: /srv/nfs
    accessKey: ""
    secretKey: ""
    resources:
      requests:
        cpu: "50m"
        memory: "16Gi" # defined in MinioChart
      limits:
        cpu: "500m"
        memory: "16Gi"
  schedules:
    k8s-cluster:
      schedule: 15 */6 * * *
      template:
        excludedResources:
        - persistentvolumeclaims
        - peristentvolumes
        hooks: {}
        includeClusterResources: true
        includedNamespaces:
        - '*'
        storageLocation: default
        ttl: 336h0m0s
