kubernetes:
  dashboard:
    coreDomain: "k8sboard.{{ clusterTLDomain }}"
    chartVersion: "6.0.6"
    replicas: 1
  clusterName: kubernetes
  # if the patch version is omitted, the latest available will be used (e.g., 1.23 -> 1.23.17).
  version: "1.27"
  crioVersion: "1.27"
  crioRuncVersion: "1.0.1~2"
  helm_version: "3.11.2"
  init_opts: ""
  kubeadm_opts: ""
  drainTimeout: "10m"
  updateSleepSeconds: 90
  ignoreDrainErrors: true
  ignorePreflightErrors: []
