kubernetes:
  dashboard:
    coreDomain: "k8sboard.{{ clusterTLDomain }}"
    chartVersion: "6.0.6"
    replicas: 1
  clusterName: kubernetes
  # if you define a version without a specific patch it will take the latest (for example: 1.25 results in 1.25.10)
  version: "1.26"
  crioVersion: "1.26"
  crioRuncVersion: "1.0.1~2"
  helm_version: "3.11.2"
  init_opts: ""
  kubeadm_opts: ""
  drainTimeout: "10m"
  updateSleepSeconds: 90
  ignoreDrainErrors: true
  cilium:
    version: v1.12.13
    waitTimeout: 120s
    proxyReplacement: "strict" #possible values: "disabled", "probe", "partial", "strict"
    manual_mtu: 0 # This Value Sets the MTU for cilium and applies it to a deamonset watching the mtu
  ignorePreflightErrors: []
