rook:
  enabled: true
  namespace: rook-ceph
  chartVersion: v1.11.3
  pspEnable: false
  crds:
    enabled: true
  common:
    enabled: true
  operator:
    enabled: true
    csiEnableCephFS: true
    csiEnableRBD: true
    csiEnableGRPC: true
    provisionerReplicas: 2
    monitoring:
      enabled: false
  cluster:
    enabled: true
    name: rook-ceph
    dataHostDir: /var/lib/rook
    mon:
      count: 3
      allowMultiplePerNode: false
    mgr:
      count: 2
      allowMultiplePerNode: false
    dashboard:
      enabled: true
      ssl: true
    monitoring:
      enabled: false
    storage:
      useAllNodes: true
      useAllDevices: true
    resources:
      mgr:
        limits:
          memory: "1024Mi"
        requests:
          cpu: "350m"
          memory: "768Mi"
      mon:
        limits:
          memory: "2048Mi"
        requests:
          cpu: "500m"
          memory: "1536Mi"
      osd:
        limits:
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "3072Mi"
      prepareosd:
        limits:
          memory: "4096Mi"
        requests:
          memory: "512Mi"
      crashcollector:
        limits:
          memory: "128Mi"
        requests:
          cpu: 25m
          memory: "64Mi"
      mgr-sidecar:
        limits:
          cpu: "500m"
          memory: "100Mi"
        requests:
          cpu: "100m"
          memory: "40Mi"
      logcollector:
        limits:
          cpu: "500m"
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "100Mi"
      cleanup:
        limits:
          cpu: "500m"
          memory: "1Gi"
        requests:
          cpu: "500m"
          memory: "100Mi"
  dashboard:
    enabled: true
    ingress:
      domain: "ceph.{{ clusterTLDomain }}"
      tls:
        enabled: false
        issuerName: "{{ LE_issuer_name }}"
  storageClassRBD:
    enabled: true
    name: rook-ceph-block
    failureDomain: host
    poolName: replicapool
    replicaLevel: 3
    minSize: 2
  storageClassObject:
    enabled: false
  storageClassFile:
    enabled: true
  toolbox:
    enabled: true
    name: rook-ceph-tools
  objectStorage:
    enabled: false
    ingress:
      domain: "s3.{{ clusterTLDomain }}"
      tls:
        enabled: true
        issuerName: "{{ LE_issuer_name }}"
    name: cephobjectn1
    region: eu-west-1
    failureDomain: host
    replicaLevel: 2
  filesystem:
    enabled: true
    name: rook-cephfs
    replicaLevel: 2
    minSize: 1
    failureDomain: host
    resources:
      limits:
        cpu: "1500m"
        memory: "4096Mi"
      requests:
        cpu: "100m"
        memory: "1024Mi"
