---
- name: "helm install ingress-nginx"
  kubernetes.core.helm:
    name: nginx-ingress
    chart_ref: vanillastack/ingress-nginx
    release_namespace: "{{ ingress.namespace }}"
    create_namespace: true
    wait: true
    chart_version: "{{ ingress.chartVersion }}"
    values: "{{ lookup('template', 'ingress-nginx.yaml.j2') | from_yaml }}"

- pause: 
    seconds: 15
