postgresOperator:
  enabled: false
  chartName: "postgres-operator"
  chartVersion: "1.7.1"
  namespace: "postgres-operator"
  backup:
    enabled: false
    s3:
      accessKey: nul
      secretKey: nul
      regionName: nul
      endpoint: nul
      bucketName: nul
    cron: "30 00 * * *"
