postgresOperator:
  enabled: false
  chartName: "postgres-operator"
  chartVersion: "v1.9.0"
  namespace: "postgres-operator"
  backup:
    enabled: false
    s3:
      accessKey: ""
      secretKey: ""
      regionName: ""
      endpoint: ""
      bucketName: ""
      encryption: ""
      retention: ""
    cron: "30 00 * * *"
