export default Object.freeze({
    Event_AcceptedTermsChanged: "Event_AcceptedTermsChanged",
    Event_MastersCountChanged: "Event_MastersCountChanged",
    Event_WorkersCountChanged: "Event_WorkersCountChanged",
    Event_InstallationKindChanged: "Event_InstallationKindChanged",
    Event_CopiedKeyToNodes: "Event_CopiedKeyToNodes",
    Event_GoBack: "Event_GoBack",
    Event_GoNext: "Event_GoNext",
    Event_NewViewLoaded: "Event_NewViewLoaded",
    Event_NavigationUpdated: "Event_NavigationUpdated",
    Event_InstallationRookUpdated: "Event_InstallationRookUpdated",
    Event_InstallationCFUpdated: "Event_InstallationCFUpdated",
    Event_InstallationOpenStackUpdated: "Event_InstallationOpenStackUpdated",
    Event_PrepareNavigation: "Event_PrepareNavigation",
    Event_IpAddressesUpdated: "Event_IpAddressesUpdated",
    Event_OpenStackUpdatedData : "Event_OpenStackUpdatedData",
    Event_CloudFoundryUpdatedData: "Event_CloudFoundryUpdatedData",
    Event_BaseDataUpdated: "Event_InfoDataUpdated",
    Event_NodesValidated: "Event_NodesValidated",
    Event_NodesChecked: "Event_NodesChecked",
    Event_AdditionalToolsDataUpdated: "Event_AdditionalToolsDataUpdated",
    Event_RookDataUpdated: "Event_RookDataUpdated",
    Event_ClusterDataUpdated: "Event_ClusterDataUpdated",
    Event_SubscriptionKeyUpdated: "Event_SubscriptionKeyUpdated",
    Event_GeneralSettingsChanged: "Event_GeneralSettingsChanged",
    Event_GeneralSettingsDirty: "Event_GeneralSettingsDirty",
    Event_LetsEncryptDataUpdated: "Event_LetsEncryptDataUpdated",
    Event_StartInstallation: "Event_StartInstallation",
    Event_ComplimentaryToolsDataUpdated: "Event_ComplimentaryToolsDataUpdated",

    Store_UpdateTermsAccepted: "updateTermsAccepted",
    Store_UpdateMasters: "updateMasters",
    Store_UpdateWorkers: "updateWorkers",
    Store_UpdateInstallationKind: "updateInstallationKind",
    Store_UpdateCopiedKeyToNodes: "updateCopiedKeyToNodes",
    Store_LoadedSSHKey: "loadedSSHKey",
    Store_UpdateNavigation: "updateNavigation",
    Store_UpdateGlobalNavigation: "updateGlobalNavigation",
    Store_UpdateInstallationRook: "updateInstallationRook",
    Store_UpdateInstallationCF: "updateInstallationCF",
    Store_UpdateInstallationOpenStack: "updateInstallationOpenStack",
    Store_UpdateIPAddresses: "updateIPAddresses",
    Store_OpenStackUpdateData : "openStackUpdateData",
    Store_CloudFoundryUpdateData: "cloudFoundryUpdateData",
    Store_BaseDataUpdateData: "baseDataUpdateData",
    Store_AdditionalToolsUpdateData: "additionalToolsUpdateData", 
    Store_RookUpdateData: "rookUpdateData", 
    Store_ClusterUpdateData: "clusterUpdateData",
    Store_UpdateSubscriptionKey: "updateSubscriptionKey",
    Store_UpdateGeneralSettings: "updateGeneralSettings",
    Store_UpdateLetsEncryptData: "updateLetsEncryptData",
    Store_NodesChecked: "nodesChecked",
    Store_UpdateSubscriptionPassword: "updateSubscriptionPassword",
    Store_ComplimentaryToolsUpdateData: "complimentaryToolsUpdateData",

    Network_LoadedInfo: "Network_LoadedInfo",
    Network_CheckingNodes: "Network_CheckingNodes",
    Network_WS_Response: "Network_WS_Response",
    Network_InstallationInProgress: "Network_InstallationInProgress",
    Network_KubeConfigLoaded: "Network_KubeConfigLoaded",
    Network_State_Error: "Network_State_Error",
    Network_State_Progress: "Network_State_Progress",

    Validate_IpAddress: /^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/,
    Validate_SubscriptionKeyLength: 6,
    Validate_Email: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
  })
  