---
- name: Deploy Redis
  community.kubernetes.helm:
    name: redis
    release_namespace: "{{redis.namespace}}"
    create_namespace: yes
    chart_ref: "vanillastack/redis"
    chart_version: "{{redis.chartVersion}}"
    values: "{{ lookup('template', 'redis.yaml.j2') | from_yaml }}"

