---
#- name: reconfigure repositories.registry_community
#  set_fact:
#    vanillastackRegistry: "{{ repositories.registry_community }}"
#  when: commercial.enabled != true
#
#- name: reconfigure repositories.registry_community
#  set_fact:
#    vanillastackRegistry: "{{ repositories.registry_commercial }}"
#  when: commercial.enabled

- name: install VanillasStack Helm repository
  community.kubernetes.helm_repository:
    name: vanillastack
    repo_url: https://{{ repositories.registry_community }}/chartrepo/vanillastack
  when: commercial.enabled != true
  ignore_errors: yes

- name: install VanillasStack Helm repository - commercial
  community.kubernetes.helm_repository:
    name: vanillastack
    repo_url: https://{{ repositories.registry_commercial }}/chartrepo/vanillastack
    repo_username: "robot${{commercial.username}}"
    repo_password: "{{commercial.key}}"
  when: commercial.enabled
  ignore_errors: yes

- name: update repo
  command: "helm repo update"
