--- 
- name: check lb ip
  command: "ping -c 1 -t 60 {{ loadbalancerIP }}"
  register: ping
  ignore_errors: true

- debug:
    msg: "{{ loadbalancerIP }} is not reachable via Ping"
  when: not ping.rc == 0

- name: check dns entry
  debug:
    msg: "{{ lookup('dig', clusterTLDomain)}}"

