---
keycloak:
  enabled: false
  namespace: keycloak
  externalDatabase: false
  postgres:
    size: "20Gi"
    replicas: 2
    version: "12"
    maxConnections: 400
    backup:
      enabled: false
      cronjob: "30 */2 * * *"
  ingress:
    enabled: false
    publicDomain: "keycloak.{{ clusterTLDomain }}"
  realm:
    name: "{{ clusterTLDomain }}"
    id: "{{ clusterTLDomain }}"
