---
- name: install monitoring
  hosts: master[0]
  gather_facts: true
  roles:
  - role: prepare-registry
    when: vanillaservices.monitoring_enabled
  - role: install-monitoring
    action: operator
    when: vanillaservices.monitoring_enabled
