---
- name: Deploy Postgres-Operator
  kubernetes.core.helm:
    name: postgres-operator
    chart_ref: "vanillastack/{{postgresOperator.chartName}}"
    release_namespace: "{{postgresOperator.namespace}}"
    chart_version: "{{postgresOperator.chartVersion}}"
    create_namespace: true
    values: "{{ lookup('template', 'operator.yaml.j2') | from_yaml }}"

- name: Create operator configs
  template:
    src: operator-config-yaml.j2
    dest: /tmp/operator-config-yaml

- name: Load config
  kubernetes.core.k8s:
    src: /tmp/operator-config-yaml
    state: present
    wait: true
