---
- name: Deploy Postgres-Operator
  community.kubernetes.helm:
    name: postgres-operator
    chart_ref: "vanillastack/{{postgresOperator.chartName}}"
    release_namespace: "{{postgresOperator.namespace}}"
    chart_version: "{{postgresOperator.chartVersion}}"
    create_namespace: yes
    values: "{{ lookup('template', 'operator.yaml.j2') | from_yaml }}"

- name: create operator configs
  template:
    src: operator-config-yaml.j2
    dest: /tmp/operator-config-yaml

- name: load config
  k8s:
    src: /tmp/operator-config-yaml
    state: present
    wait: true

