---
- name: Deploy Redis Sentinel
  kubernetes.core.helm:
    name: redis-cluster
    release_namespace: "{{redis.namespace}}"
    create_namespace: true
    chart_ref: "vanillastack/redis"
    chart_version: "{{redis.chartVersion}}"
    values: "{{ lookup('template', 'redis.yaml.j2') | from_yaml }}"
    update_repo_cache: true
  retries: 3
  delay: 10
