---
- name: Download velero client
  get_url:
    url: "https://github.com/vmware-tanzu/velero/releases/download/{{velero.version}}/velero-{{velero.version}}-linux-amd64.tar.gz"
    dest: /tmp/velero.tgz

- name: untar velero
  unarchive:
    src: /tmp/velero.tgz
    dest: /tmp/
    remote_src: yes

- name: mv velero binary
  copy:
    src: /tmp/velero-{{velero.version}}-linux-amd64/velero
    dest: /usr/local/bin/velero
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: cleanup
  file:
    name: "{{item}}"
    state: absent
  with_items:
    - /tmp/velero.tgz
    - /tmp/velero-{{velero.version}}-linux-amd64
